Configurable FU used by `GenParams`
kuznia-rdzeni/coreblocks pull request #209
Opened 2023-01-24 22:08 UTC by speederking07

Goal of this PR is to create mechanism for easy configuration of FU used in core.

- [x] new field with FU configuration in `GenParams`
- [x] add core generation based on FU configuration
- [x] implement dependency injection (kinda implemented)
- [x] find new naming scheme for FU and Blocks
- [x] test commit method
- [x] add cross verification for isa and FU configuration

2023-02-07 10:47 UTC, tilk commented on coreblocks/core.py
> +# TODO: Move somewhere else
Maybe it's time to move it somewhere else?

2023-02-07 10:47 UTC, tilk commented on coreblocks/core.py
> +                self.branch_result = br_collector.get_single
This looks like something to be generalized, as there is an almost identical block just a few lines below.

Also, the special case for length one makes me feel uneasy, but I understand it will simplify the connection diagram. Maybe some general way of doing this should be created, but this is not a priority.

2023-02-07 10:47 UTC, tilk commented on coreblocks/fu/jumpbranch.py
> +from coreblocks.utils.protocols import FuncUnit
Weird place for an import.

2023-02-07 10:47 UTC, tilk commented on coreblocks/lsu/dummyLsu.py
> +from coreblocks.utils.protocols import FuncBlock
Weird place for an import.

2023-02-07 10:47 UTC, tilk commented on coreblocks/lsu/dummyLsu.py
> +            raise Exception("LSU requires wishbone bus, but it was not provided as dependency")
There should be a way to avoid writing this. Maybe raise the exception from `ComponentDependencies`?

2023-02-07 10:47 UTC, tilk commented on coreblocks/params/fu_params.py
> +            return None
This is kinda like `defaultdict`.

Also, `None` is in many (all?) places not really useful - if there is a dependency, you can't do anything with `None` other than raising an exception.

Also, type annotations.

2023-02-07 10:47 UTC, tilk commented on coreblocks/params/fu_params.py
> +        self.dependencies = dependencies
Is there a way to make dependencies typed? Maybe the keys should not be strings, but carry some type information with them?

2023-02-07 10:47 UTC, tilk commented on coreblocks/params/fu_params.py
> +        ...
This should be an ABC.

2023-02-07 14:33 UTC, tilk commented
I think we should focus on merging this, and leave improvements to the DI stuff for later PRs, especially if they would delay you.

2023-02-07 21:49 UTC, speederking07 commented
I agree we need to generalize unifying methods for `RSBlocks` , however this commit is already large enough. So I will leave this improvement as well as adding comments to next PRs.

2023-02-08 11:45 UTC, tilk commented
> I agree we need to generalize unifying methods for `RSBlocks` , however this commit is already large enough. So I will leave this improvement as well as adding comments to next PRs.

Oh pleeeease, that's not a big deal. After merging #227, which makes `Collector` conform to the method combinator interface (which it was supposed to anyway), the required change will be trivial.

2023-02-08 11:46 UTC, tilk commented on coreblocks/params/fu_params.py
> +        ...
This wasn't implemented.

2023-02-08 11:55 UTC, tilk commented on coreblocks/params/fu_params.py
> +        ...
Should be ABCs, you forgot to do that.

2023-02-08 11:55 UTC, tilk commented on coreblocks/stages/func_blocks_unifier.py
> +                self.commit = commit_product.method
This copy-paste should be eliminated. Common code should be abstracted in a function.

2023-02-08 11:55 UTC, tilk commented on coreblocks/lsu/dummyLsu.py
> +        return LSUDummy(gen_params, dependencies.get(Key[WishboneMaster]("wishbone_bus")))
Construct the keys globally, and use their identity for indexing - instead you are basically losing the type safety.

2023-02-08 11:55 UTC, tilk commented on coreblocks/params/fu_params.py
> +    def __init__(self, **dependencies):
Kwargs are not appropriate for this use, as you lack the required type information there.

2023-02-08 11:55 UTC, tilk commented on coreblocks/params/fu_params.py
> +        if key.name not in self.dependencies:
`dependencies` should be indexed by keys, not their names.

2023-02-08 11:55 UTC, tilk commented on coreblocks/params/fu_params.py
> +        self.name = name
Because keys should be constructed once, you could get the names automatically from the definition. See, for example, how `Method` does this.

2023-02-09 17:43 UTC, speederking07 commented
@tilk now it should look like your idea from last class. I am not the biggest fan of mutable argument for collecting outputs, but it look nice so I can accept this version.

2023-02-09 18:53 UTC, tilk commented on coreblocks/params/fu_params.py
> +        ...
No, this is not enough. Please read the fine documentation.
https://docs.python.org/3/library/abc.html

2023-02-09 20:22 UTC, speederking07 commented on coreblocks/params/genparams.py
> +            import coreblocks.stages.rs_func_block as rs_block
I agree it is ugly. but this import cannot be moved, because is causes circular import. I can try to replace this import with some `Protocol`.

2023-02-09 20:30 UTC, tilk commented on coreblocks/stages/func_blocks_unifier.py
> +        self.extra_outputs = {}
Types are missing.

2023-02-09 20:50 UTC, tilk commented
I thought we agreed to leave complex changes for later. Now this PR will be stuck for a next week or two in CR 🤣

2023-02-09 21:15 UTC, speederking07 commented
I also thought we will keep it simple, but since:
> Oh pleeeease, that's not a big deal. After merging https://github.com/kuznia-rdzeni/coreblocks/pull/227, which makes Collector conform to the method combinator interface (which it was supposed to anyway), the required change will be trivial.

Plus you wanted to have type safe dependencies, removed duplicated code fragment with method unifying, in that case it was as easy to fix every issue own as to create this more universal approach. All this requirements were screaming to me that I need to add this final piece to this code.

2023-02-09 23:28 UTC, tilk commented
I wanted to have the code duplication removed, that's all. For other comments I marked which ones are to be postponed. The design you proposed now is by no means perfect, and will need to go through another round or two of CR, while the previous one was satisfactory for now. Other team members need to take a look, too - but exams might delay that.

2023-02-10 14:26 UTC, speederking07 commented
I would leave it as it currently is, I don't think that changes are that fundamental (it took me an hour to implement). But if you want I can go back to protocols, as I think type safe dependencies should stay. But I really see no point in abstracting function which will need to take a lot of parameters, only to be replaced with next PR one week later.

2023-02-21 10:35 UTC, tilk commented
I think that I'll let others decide on this one. We can always change this later, and we certainly don't want this change to land into pull request limbo.

2023-02-25 17:24 UTC, lekcyjna123 requested changes
This PR looks great! I am for merging it with the current state (so with dependency injection), because in my opinion it is very readable.

There are two points which should be fixed before merge:
- you changed GenParams interface, but didn't change benchmark scripts, so benchmark will fail on this PR
- now there are two definitions of OpType class, one of them should be removed

On the last meeting you have asked how we can connect (make an unifier) commit. I would propose two change commit interface so that it will return a bit 0 or 1. This will mean that commit ended with success or not. So an unifier will call all commit methods and will wait for the answer. If all will return OK, than unifier will return OK also.

2023-02-25 17:24 UTC, lekcyjna123 commented on test/fu/test_mul_unit.py
> +def gen_test_params(param):
Why you added that?

2023-02-26 22:17 UTC, speederking07 commented on coreblocks/params/fu_params.py
> +        ...
Hmm maybe that is a good idea. I will change it

2023-02-26 22:17 UTC, speederking07 commented on coreblocks/params/genparams.py
> +        func_units_config: list[BlockComponentParams],
Thx, I missed that

2023-02-26 22:18 UTC, speederking07 commented on coreblocks/params/isa.py
> -    "OpType",
Thx, removed

2023-02-26 22:19 UTC, speederking07 commented on coreblocks/params/fu_params.py
> +    def set_output(self, key: type[OutputKey], output: Method) -> ComponentConnections:
I changed it to `register_method` but still not sure if it is a good name.

2023-02-26 22:22 UTC, speederking07 commented on coreblocks/stages/func_blocks_unifier.py
> +                self.extra_outputs[key.method_name()] = unifier.method
The whole idea is that method_name needs to be unique in another case we will have problems with method name shadowing. Key names are unique but then there will be an issue with ugly method names. If some knows how to enforce uniqueness here I would be grateful

2023-02-26 22:24 UTC, speederking07 commented on test/fu/test_mul_unit.py
> +def gen_test_params(param):
Because in most tests we use `GenParams` only for constans like number of RS, but since I changed `GenParams` they no longer gets number of RS as parameter and it would be tedious to create mockup RS config for every test only to set number of RSes.

2023-02-26 22:30 UTC, speederking07 commented
I will create this waiting for success unifier tomorrow.

2023-02-27 08:24 UTC, tilk commented
> I will create this waiting for success unifier tomorrow.

But do it in another PR, pretty please?

2023-02-27 09:08 UTC, speederking07 commented
> But do it in another PR, pretty please?

Good point. Maybe it should go with changes to LSU commit? @lekcyjna123 what do you think?

2023-02-27 09:44 UTC, tilk requested changes

2023-02-27 09:44 UTC, tilk commented on coreblocks/stages/func_blocks_unifier.py
> +        return self.extra_outputs[item]
I don't like this at all! The `Core` class has a very specific requirements (`get_result` and `update`), and references them directly. Here, everything is processed implicitly (even things that might not be required from the core, but were added in future development. This hurts clarity too. I would just handle `get_result` and `update` explicitly. The unifier construction code should be abstracted, so that it could be used in other places.

These changes would also fix the problem described by @lekcyjna123, as key manipulation magic would disappear.

2023-02-27 09:44 UTC, tilk commented on coreblocks/params/fu_params.py
> +        return self.outputs
Smelly, and unnecessary, see comment on `FuncBlockUnifier`.

2023-02-27 09:44 UTC, tilk commented on coreblocks/params/fu_params.py
> +    def register_method(self, key: type[MethodKey], output: Method) -> ComponentConnections:
It's ugly that `MethodKey` and `DependencyKey` are two different things. It would be best if the same logic could handle both.

Actually, there is a slight variation in logic which is still needed - some keys are associated with exactly one value, and some collect multiple values from different components. Maybe there should be two distinguished kinds of keys - singleton keys and multi-keys?

2023-02-27 09:44 UTC, tilk commented on coreblocks/params/fu_params.py
> +    pass
Consider the following changes:

* Make keys [dataclasses](https://docs.python.org/3/library/dataclasses.html) (with `frozen=True` to enable hashing).
* Use instances of keys in `ComponentConnections`, not key types.

2023-02-27 09:44 UTC, tilk commented on coreblocks/params/fu_params.py
> +        raise NotImplementedError()
I currently see two possible ways of handling the awkwardness of `MethodKey` (strange implicit dependencies, name collision issues, etc.):

* Get rid of it entirely, make a generic way of associating multiple values with one key instead, handle each method explicitly. (This solution has the upside of being simple, but it misses an abstraction opportunity.)
* Find a way to move the unifier construction logic closer to `MethodKey`, while somehow keeping the genericity of keys.

Because this PR lingers for so long, I currently prefer the option A. Otherwise, I feel this PR will remain in limbo even longer.

2023-02-27 10:16 UTC, speederking07 commented on coreblocks/params/fu_params.py
> +    def set_dependency(self, key: type[DependencyKey[T]], dependency: T) -> ComponentConnections:
In my opinion is the bast way to ensure type safety. Using types as keys ensures their global uniqueness, and makes sure no one will creates his own instance with incompatible type. And the only drawback is that it might take a bit longer time to create new key.

2023-02-27 10:23 UTC, speederking07 commented on coreblocks/stages/func_blocks_unifier.py
> +        return self.extra_outputs[item]
I think I don't get it. `get_result` and `update` are explicit in lines 24-28. I see a problem with that it is not obvious which method are available, but since they depends of `blocks`, I see no way how to fix it. Please, elaborate how I can make it more abstract.

2023-02-27 10:28 UTC, speederking07 commented on coreblocks/params/fu_params.py
> +    def register_method(self, key: type[MethodKey], output: Method) -> ComponentConnections:
But they have really different responsibility. Dependency can be anything, and I assume that they can be used multiple times without an issue. And MethodKeys, and handle only extra methods, and need to unify its interface. For me this is strong enough distinction.

2023-02-27 10:41 UTC, speederking07 commented on coreblocks/params/fu_params.py
> +        raise NotImplementedError()
I will get git of them entirely. Can I assume that every method of RS block and FU units with this same name has this same interface, and basically this same responsibility. If so, I could create a dictionary, with names as keys, and unifiers as values in order to handle it.

2023-02-27 11:12 UTC, tilk commented on coreblocks/params/fu_params.py
> +    def set_dependency(self, key: type[DependencyKey[T]], dependency: T) -> ComponentConnections:
> And the only drawback is that it might take a bit longer time to create new key.

The other drawback is, as I mentioned, that value-parametrized (in other words, dynamically created) keys are impossible. There is also the philosophical opposition: keys are classes without usable instances.

2023-02-27 11:24 UTC, tilk commented on coreblocks/stages/func_blocks_unifier.py
> +        return self.extra_outputs[item]
Forgot to mention `branch_result` and `commit`.

Again, the problem is that `core` knows exactly what it wants, and can grab it by name. While here you have an indirection which might seem beneficial, but is actually useless: you have to handle these and only these methods that are needed in `core`. The dynamic `for` is actually harmful: if the required keys are missing, you will get an error in `core` (and not here!), and if there are extra keys (possibly needed elsewhere), they will be handled here regardless. You implicitly entangle `core`, this module, and method keys.

> Please, elaborate how I can make it more abstract.

"Abstracting code" is an elaborate way to say "make it a separate function or method somewhere".

2023-02-27 14:01 UTC, speederking07 commented on coreblocks/params/fu_params.py
> +    def set_dependency(self, key: type[DependencyKey[T]], dependency: T) -> ComponentConnections:
I agree to that philosophical opposition it is kinda wierd to use classes this way. But I see no reason to dynamically create key. I thought that whole idea is that keys should be global, otherwise we will end up with `DependencyKey[A]('dependency1')` and `DependencyKey[B]('dependency1')` for this same dependency. Putting them as classes makes sure this same key will always have this same underlying type.

2023-02-27 15:03 UTC, speederking07 commented
@tilk Could you take a look if new version is at least step in good direction?

2023-03-05 16:09 UTC, lekcyjna123 commented on test/fu/test_mul_unit.py
> +def gen_test_params(param):
But this function has local scope and empty implementation and isn't used anywhere.

2023-03-05 16:30 UTC, lekcyjna123 commented on coreblocks/params/fu_params.py
> +    def set_dependency(self, key: type[DependencyKey[T]], dependency: T) -> ComponentConnections:
> The other drawback is, as I mentioned, that value-parametrized (in other words, dynamically created) keys are impossible.

Value-parametrized keys in such scenario wouldn't be impossible. In Python we have functions `compile` and `exec` which allow us to add new code in runtime. So in case of keys defined by classes, this would allow us to define new class as a string of code and next execute it in our context to create new class. Ugly, but possible.

2023-03-05 18:13 UTC, speederking07 commented on test/fu/test_mul_unit.py
> +def gen_test_params(param):
Oh, you're right. I must have created it by mistake.

2023-03-05 20:44 UTC, lekcyjna123 commented
I have prepared my own PoC of keys system based on speederking07 solution. Please see to #235 .

2023-03-09 15:28 UTC, tilk commented
#235 now contains combined changes of @lekcyjna123 and mine. Please check them out.

2023-03-10 13:43 UTC, tilk approved these changes
Let's merge this!

2023-03-10 19:22 UTC, lekcyjna123 approved these changes

2023-03-13 13:32 UTC, merged