Make Sphinx CI fail on errors and warnings
kuznia-rdzeni/coreblocks pull request #241
Opened 2023-03-09 13:12 UTC by tilk

This PR improves error detection in CI for documentation build, will help catch docstring problems sooner.

2023-03-10 10:03 UTC, Kristopher38 approved these changes

2023-03-13 18:25 UTC, lekcyjna123 requested changes

2023-03-13 18:25 UTC, lekcyjna123 commented on ci/build-docs.sh
> +scripts/build-docs.sh -d "$DOCS_DIR" -o "$BUILD_DIR" || exit 1
Instead of `|| exit 1` please use `set -e` to terminate script on first error.

2023-03-14 12:42 UTC, tilk commented on ci/build-docs.sh
> +scripts/build-docs.sh -d "$DOCS_DIR" -o "$BUILD_DIR" || exit 1
If you prefer it that way, sure.

2023-03-14 18:21 UTC, lekcyjna123 approved these changes

2023-03-15 09:07 UTC, merged