ZBA extension built into ALU
kuznia-rdzeni/coreblocks pull request #246
Opened 2023-03-14 13:14 UTC by wojpok

2023-03-14 15:29 UTC, tilk reviewed
You also need to extend `frontend/decoder.py`, but otherwise, pretty nice change.

2023-03-14 15:29 UTC, tilk commented on coreblocks/params/optypes.py
> +        OpType.ADRESS_GENERATION,
```suggestion
        OpType.ADDRESS_GENERATION,
```

2023-03-14 15:29 UTC, tilk commented on coreblocks/params/optypes.py
> +    ADRESS_GENERATION = auto()
```suggestion
    ADDRESS_GENERATION = auto()
```

2023-03-14 15:29 UTC, tilk commented on coreblocks/fu/alu.py
> +    optypes = {OpType.ARITHMETIC, OpType.COMPARE, OpType.LOGIC, OpType.SHIFT, OpType.ADRESS_GENERATION}
```suggestion
    optypes = {OpType.ARITHMETIC, OpType.COMPARE, OpType.LOGIC, OpType.SHIFT, OpType.ADDRESS_GENERATION}
```

2023-03-16 14:40 UTC, wojpok commented
I've just fixed all the typos and extended frontend decoder and it seems like this draft is ready to be converted to pull request

2023-03-16 18:48 UTC, tilk approved these changes

2023-03-17 11:46 UTC, tilk requested changes

2023-03-17 11:46 UTC, tilk commented on coreblocks/params/isa.py
> +    SH3ADD = 0b0000011
Change encoding of SHADD instructions according to the spec.

2023-03-17 14:33 UTC, tilk commented on coreblocks/params/isa.py
> +    SHADD = 0b0010000
Let's use the names from the spec: SH1ADD, SH2ADD and SH3ADD (their value is the same, but so what, same thing happens with AND, OR for example).

2023-03-17 14:41 UTC, tilk approved these changes

2023-03-17 14:43 UTC, wojpok commented on coreblocks/params/isa.py
> +    SHADD = 0b0010000
Resolved. In the future we may want to rename some other parameters as well, since there are some other operations in ALU that share parameter names

2023-03-17 15:41 UTC, tilk commented
Damn it, that's another detail missed! I sure hope it's the last one.

2023-03-18 19:05 UTC, merged