Make the fetch unit use instruction cache
kuznia-rdzeni/coreblocks pull request #271
Opened 2023-03-30 22:31 UTC by xThaid

Not working yet, but I am publishing it in case someone wants to take a look.

2023-04-02 20:25 UTC, xThaid commented on coreblocks/frontend/fetch.py
> +        # Signals used for debugging purposes
Do we actually want to keep them?

2023-04-03 08:28 UTC, tilk commented on coreblocks/frontend/icache.py
> +        with m.FSM(reset="LOOKUP") as fsm:
Shouldn't this be in #258?

2023-04-03 08:29 UTC, tilk commented on coreblocks/frontend/icache.py
> +        with m.FSM(reset="LOOKUP") as fsm:
Shouldn't this be in #258?

2023-04-03 08:31 UTC, tilk approved these changes
Looks okay.

2023-04-03 17:41 UTC, lekcyjna123 commented
You have completely rewritten Fetch unit. Instead of that I would rather have a new unit, so that we can choose on generation time if we want to use cache or connect core directly to memory.

2023-04-04 08:12 UTC, tilk commented
> You have completely rewritten Fetch unit. Instead of that I would rather have a new unit, so that we can choose on generation time if we want to use cache or connect core directly to memory.

Even though we would like to have at least a small instruction cache for most cases, I agree, it's more fitting for our philosophy to have alternative fetch units.

2023-04-09 09:42 UTC, xThaid commented
> You have completely rewritten Fetch unit. Instead of that I would rather have a new unit, so that we can choose on generation time if we want to use cache or connect core directly to memory.

> Even though we would like to have at least a small instruction cache for most cases, I agree, it's more fitting for our philosophy to have alternative fetch units.

If we want to switch between big modules (like the fetch unit), shouldn't we have more strict interfaces? Right now, the fetch unit (and other big modules) are loosely defined, i.e. attributes are accessed throughout the codebase and we don't really specify what should be the names. Maybe we can use Python Abstract Base classes.

2023-04-09 12:11 UTC, lekcyjna123 commented
As for know we don't use ABC for interface in FUs and they all have the same interface, but I think that it is a good idea, to somehow ensure, that interface is correct on each HW block.

2023-04-10 09:37 UTC, tilk commented
> As for know we don't use ABC for interface in FUs

But we (currently) use protocols for type checking. I'm still torn between ABCs and protocols here: ABCs are more explicit (you need to declare something is an instance of a given ABC), while protocols are more implicit.

2023-04-12 12:22 UTC, tilk commented
Branch probably requires a `rebase --onto`.

2023-04-16 20:09 UTC, tilk commented
I think that the most probable reason for the tests failing is that the sizes of the memory regions need to be rounded up.

2023-04-21 00:38 UTC, Kristopher38 requested changes

2023-04-21 00:38 UTC, Kristopher38 commented on coreblocks/frontend/fetch.py
> +            with m.Elif(res.error == 0):
Really nitpicking but could you remove that empty line there? You had me thinking that `Elif` was actually a separate `If` for a while

2023-04-21 00:38 UTC, Kristopher38 commented on test/frontend/test_fetch.py
> +                    continue
I don't fully understand this part yet. Can this condition happen in the current core implementation?

2023-04-21 00:38 UTC, Kristopher38 commented on test/test_core.py
> +        infloop_addr = (len(self.instr_mem) - 1) * 4
Why `self.gp.isa.ilen_bytes` got changed to `4`?

2023-04-21 00:38 UTC, Kristopher38 commented on test/test_core.py
> +        # We add JAL instruction at the end to effictively create a infinite loop at the end of the program.
typo - `effectively`

2023-04-21 00:38 UTC, Kristopher38 commented on test/test_core.py
> +        while (yield self.m.core.fetch.pc) != infloop_addr:
I see a bug here - later in the code you build an instruction sequence of *some* length, supply it to `TestElaboratable` and then align it to the length of the cache line. If the last JAL instruction doesn't end up at `infloop_addr` you'll loop forever (until simulation times out).

We had plans to refactor how these tests behave (`halt_pc` was a temporary solution) - the way we envisioned it was we would monitor some register dedicated to signaling test finish by writing nonzero value to it, or something along those lines. You can choose whether or not to implement it in this PR.

2023-04-24 20:44 UTC, xThaid commented on test/frontend/test_fetch.py
> +                    continue
Yes, the fetch unit speculatively fetches instructions, which may not end up executed.

2023-04-24 20:50 UTC, xThaid commented on test/test_core.py
> +        infloop_addr = (len(self.instr_mem) - 1) * 4
`self.gp.isa.ilen_bytes` defines the maximum instruction width, so using that variable here is definitely incorrect. And since in this particular test we use only instruction of size 4 bytes, I hardcoded 4 here.

2023-04-24 20:55 UTC, xThaid commented on test/test_core.py
> +        while (yield self.m.core.fetch.pc) != infloop_addr:
Alignment is done in `TestElaboratable`, so `infloop_addr` is calculated using the unaligned value. I do agree however that the current way of signaling the end of the test is not perfect. But I will leave it to another PR.

2023-04-24 21:05 UTC, xThaid commented
I have found the bug -- the cache wasn't cleaned on reset.

- Under Icarus Verilog, all tests (so in particular the first one as well) failed, so perhaps iverilog doesn't initialize memory and propagates uninitialized signals?
- Under Verilator, the first test passed, but the following ones failed, as the data in the cache was outdated.

2023-04-25 18:56 UTC, xThaid commented
Now the cache can be turned off using the configuration. Some of the changes are in the separate PR #307

2023-04-27 12:40 UTC, Kristopher38 commented on coreblocks/frontend/fetch.py
> +                m.d.sync += discard_next.eq(0)
I looks like `discard_next` is unused (?)

2023-04-27 12:42 UTC, Kristopher38 approved these changes

2023-04-27 13:43 UTC, merged