Fix FreeRF FIFO initialization
kuznia-rdzeni/coreblocks pull request #279
Opened 2023-04-07 08:58 UTC by piotro888

This is a fix for issues reported in #268. Let's hope all tests will pass now!
The issue was that `init` parameter from Amaranth's `Memory` initializes memory to `init` only on full power cycle instead of reset (unlike everything else).  From docs: `Initial values. At power on, each storage element in this memory is initialized to the corresponding element of init`. Cocotb tests were the first test to actually use the reset signal. (debugging log in teams channel)

This PR initializes FreeRF with simple transaction that runs on reset and removes misleading init parameter from `BasicFIFO`.
Possible improvements (let me know what you think):
* `Retirement` Transcation could be `scheduled_before` this init transaction. This way it would not delay core by blocking retirement, and supply new regs when they are needed (and we can a couple cycles of delay in fibonacci mem test). That would involve passing retirement transaction from `elaborate` stage some dependecy key (it cannot be declared in constructor), so I have mixed feelings about that
* Make a variant of BasicFIFO that uses `Array` of Signals instead of `Memory`, that can be `init`ed like we want

2023-04-07 09:57 UTC, tilk requested changes

2023-04-07 09:57 UTC, tilk commented on test/utils/test_fifo.py
> +        expq = deque()  # first expected element is at the start of init_list
The comment is outdated.

2023-04-07 09:57 UTC, tilk commented on test/utils/test_fifo.py
> +        ("power", 4, 0),
The third argument is not used anymore.

2023-04-07 10:19 UTC, tilk approved these changes

2023-04-09 08:22 UTC, lekcyjna123 approved these changes

2023-04-09 09:50 UTC, merged