Set logical registers to 0 if they are not valid
kuznia-rdzeni/coreblocks pull request #282
Opened 2023-04-08 13:33 UTC by piotro888

@tilk another fix for #268 .

Decoder produced `rl_s1_v, rl_s2_v and rl_rd_v` fields but they were not used anywehere.
It caused allocation of random registers (only a waste of resources, not breaking things), but Jump/Branch unit was the first FU that sometimes produced results (AUIPC) and sometimes not. In this case computed branch result was always commited to random register (even if it was not valid like in BGEU).

This PR changes muxes invalid registers to 0 in decoder, so they have no effect on core (writes ignored, allocation ignored, reads ignored).

I also removed the ` rl_**_v` field from layout, pushed through whole core, because I don't feel like it will be useful anywhere. Functional Units only use source fields to computation based on FUs internal decoders. With this PR, RSes would not wait for 0 register (and I see no point in pushing random registers values through core), and in case of J/B unit produced result would be ignored if rd is not valid.

2023-04-08 13:52 UTC, tilk commented
I also discovered this problem, but went deeper into fixing it, and discovered a problem with decoding CSR registers.

https://github.com/kuznia-rdzeni/coreblocks/pull/268/commits/21ecc666bca2df32fc7b53c738813d545886b9f9

2023-04-08 16:43 UTC, tilk commented
I think your solution looks nicer, but you could also change ‘test_decoder’ to check that the valid signal is 1 if and only if the register is expected (currently only the implication expected -> valid is checked).

2023-04-09 08:00 UTC, tilk approved these changes

2023-04-09 08:36 UTC, lekcyjna123 requested changes

2023-04-09 08:36 UTC, lekcyjna123 commented on test/frontend/test_decoder.py
> -                self.assertEqual((yield self.decoder.rs1), test.rs1)
Typo. You have removed the test for correctness of value inside of `decoder.rs{1,2}`. Instead of that you check two times the valid bit.

2023-04-09 08:37 UTC, xThaid approved these changes

2023-04-09 09:52 UTC, tilk requested changes

2023-04-09 09:52 UTC, tilk commented on test/frontend/test_decoder.py
> -                self.assertEqual((yield self.decoder.rs2), test.rs2)
Same problem here.

2023-04-10 10:04 UTC, piotro888 commented on test/frontend/test_decoder.py
> -                self.assertEqual((yield self.decoder.rs1), test.rs1)
ahh, such a stupid typo. fixed

2023-04-10 10:06 UTC, lekcyjna123 approved these changes

2023-04-10 12:49 UTC, tilk approved these changes

2023-04-10 12:53 UTC, merged