Changes in utils
kuznia-rdzeni/coreblocks pull request #304
Opened 2023-04-23 17:25 UTC by lekcyjna123

Here is set of changes in common code which was a part of #293. Changes:
- name anonymous submodules to have better printing in gtkwave (in transactron and in `SimpleTestCircuit`)
- Add `MemoryBank`
- Add `Serializer`
- Extend interface of `SimpleTestCircuit`
- improve stubs
- changes in `BasicFifo` interface

ToDo:
- [] Add doc strings

If needed I can split this PR into smaller once.

2023-04-23 19:55 UTC, tilk commented
Docstrings are needed, it's not clear on the first glance what the new modules do.

2023-04-23 20:17 UTC, tilk commented on test/common.py
> +                        m.submodules[name + str(i)] = self._io[name + str(i)]
No, not these `list` shenanigans again. I'm starting to think that traversing some random lists is something possibly painful. More points against this:

* Possibly not generic enough. Someday, you might want lists of lists. Or dicts. Or something else.
* The string manipulation business for keys leads to ugly code and possibly errors.
* The change, together with the other one, makes the `SimpleTestCircuit` not that simple anymore.

2023-04-23 20:17 UTC, tilk commented on test/common.py
> +        self.external_submodules = external_submodules
I'm not certain I like this. This feature is used to pass `TestbenchIOs` for methods to be mocked. I believe there is a better abstraction to be found.

2023-04-26 08:44 UTC, lekcyjna123 commented
I have added doc-strings so this pull request is ready for review in my opinion. I will be thinking how to provide better abstraction for operating on collections of methods and how to prepare TestbenchIO for method stubs.

2023-04-26 10:51 UTC, lekcyjna123 commented
> No, not these list shenanigans again. I'm starting to think that traversing some random lists is something possibly painful. More points against this:
>
 >  - Possibly not generic enough. Someday, you might want lists of lists. Or dicts. Or something else.
 >  - The string manipulation business for keys leads to ugly code and possibly errors.

I agree with that points. But we have to find something out, because there will be a lot of such code in vector core and in future in superscalar parts. So to start the discussion here is my first alternative proposition:

### MethodContainer protocol

In this solution we can define our own protocol which will describe a class which can store collection of methods. In basic implementation it will be a wrapper on list, but with added some methods to abstract away some problems.

Functionalities which we need:
- get debug signals from all methods
- get all methods with names to put methods as a submodules
- add new elements to the container

2023-04-26 11:24 UTC, tilk commented
> MethodContainer protocol

This looks like a great idea. Probably a generic wrapper could be created, which would work for various data structures. Or alternatively, maybe, a combinator approach would also work? Regardless, I think that "adding" shouldn't be part of the interface, as this depends on the underlying data structure.

2023-04-26 11:27 UTC, lekcyjna123 commented
Ok. So I will prepare some proof of concept.

2023-04-28 07:35 UTC, tilk commented on coreblocks/transactions/core.py
> +    add_next_submodule(m, sched, "_transactron_sheduler")
```suggestion
    add_next_submodule(m, sched, "_transactron_scheduler")
```

2023-04-28 07:35 UTC, tilk commented on coreblocks/transactions/lib.py
> +        self.read_resp.schedule_before(self.read_req)
I know we don't have this standardized, but I think I prefer having this in `elaborate`, near the method definitions. Why? Because then it's close to the things whose correct behavior depends on the scheduling order.

2023-04-28 07:35 UTC, tilk commented on coreblocks/transactions/lib.py
> +                return self.serialized_resp_method(m)
This has one problem: if one of the response received is stubbornly stopped for some reason, the others can't run, even though their responses are already in the queue. Why not multiple queues? This would still preserve relative order for each user., without introducing unnecessary blocking.

2023-04-28 07:38 UTC, tilk commented
By the way, this is one hell of a PR, mixing multiple unrelated changes.

2023-04-28 08:14 UTC, Arusekk requested changes
This is a massive PR meaning-wise.  Such changes should be IMO split into several functional parts.
There are 8 distinct parts to it:
* A new MemoryBank library module.
* A new Serializer library module.
* Changes in Forwarder library module.
* Stub updates.
* Changes from `submodules += mod` to `submodules.mod = mod`.
* The weird `"_name" + str(i) for i in range()` design pattern helping the above change maybe?  I left a comment for that specifically.
* A functional change for accepting some `external_submodules`.
* A nice debug message change (I mean `f'Trying to use method {} which is not defined yet'`).

I'm sure 2 distinct parts *can* be sometimes groupped together, if they are helpful or depend on each other, but maybe they should be split into 2 commits, lkml-style.
But 8... they should be just split into at least 2 PRs as far as I'm concerned.
Especially if they are not some huge changes, where this would be particularly cumbersome to do.

We demand easier reviews! 😄

2023-04-28 08:14 UTC, Arusekk commented on coreblocks/utils/utils.py
> +    m.submodules[name + str(i)] = sub
I think if we are doing this, then we should not be doing this.

Why not use a separate module, and then put everything like this underneath without any names?  Does this approach have any obvious benefit?

2023-04-28 10:44 UTC, xThaid commented on coreblocks/transactions/lib.py
> +        @def_method(m, self.read_req, ready=~read_output_valid | self.read_resp.run)
`self.read_resp.run` creates a combinatorial path between the request and response methods. Not only it may extend the critical path, but also the user of this module may inadvertently create a loop. I think this path can be cut by using Forwarder.

2023-04-30 13:46 UTC, lekcyjna123 commented
As requested changes from this review have been split into set of smaller reviews #314 #317 #319. I change status of this PR to draft till these 3 PRs will be merged.

2023-05-06 11:20 UTC, tilk commented on coreblocks/transactions/lib.py
> +                return self.serialized_resp_method(m)
Actually, this can probably be handled by external queues.

2023-05-06 13:59 UTC, lekcyjna123 commented on coreblocks/transactions/lib.py
> +        m.submodules.write_port = write_port = mem.write_port()
Yes.
https://github.com/amaranth-lang/amaranth/blob/main/examples/basic/mem.py

2023-05-06 14:59 UTC, lekcyjna123 commented on coreblocks/transactions/lib.py
> +        @def_method(m, self.read_req, ready=~read_output_valid | self.read_resp.run)
Forwarder uses exactly the same trick, so it doesn't help for critical path. To don't create loop there is `shedule_before`.

2023-05-06 15:00 UTC, lekcyjna123 commented on coreblocks/transactions/lib.py
> +        m.d.comb += self.head.eq(read_value)
To have an interface which is in depended from inner representation.

2023-05-06 15:04 UTC, lekcyjna123 commented on test/common.py
> +                        m.submodules[name + str(i)] = self._io[name + str(i)]
Fixed with the use of ModuleConnector and recursion.

2023-05-06 15:05 UTC, lekcyjna123 commented on coreblocks/utils/utils.py
> +    m.submodules[name + str(i)] = sub
Removed

2023-05-06 15:05 UTC, lekcyjna123 commented on coreblocks/transactions/core.py
> +    add_next_submodule(m, sched, "_transactron_sheduler")
Changes done in different PR.

2023-05-06 15:05 UTC, lekcyjna123 commented on coreblocks/transactions/lib.py
> +        self.read_resp.schedule_before(self.read_req)
Fixed

2023-05-06 15:43 UTC, lekcyjna123 commented
Status of this PR is set back to ready for review, because all needed PRs have been already merged.

2023-05-07 13:34 UTC, Arusekk commented on test/transactions/test_transaction_lib.py
> +            yield from self.tick(random.randrange(rand) + 1)
inconsistent (one, 1/2)

Maybe it would be useful if it could be extracted to some mix-in class?

2023-05-07 13:34 UTC, Arusekk commented on test/transactions/test_transaction_lib.py
> +            yield from self.tick(random.randrange(1, rand + 1))
inconsistent (one, 2/2)

2023-05-07 13:34 UTC, Arusekk commented on test/transactions/test_transaction_lib.py
> +        def responser(i: int):
maybe responder?

2023-05-07 13:34 UTC, Arusekk commented on test/common.py
> +    @staticmethod
effectively a classmethod (actual cls instead of SimpleTestCircuit in the body maybe)

2023-05-08 13:52 UTC, tilk commented on test/common.py
> +    @staticmethod
Or a private function in `elaborate`, no need to pollute the attribute namespace. (I know Pythonists don't care, buuut...)

2023-05-13 15:05 UTC, lekcyjna123 commented on test/common.py
> +    @staticmethod
> Also, isn't this doing the dreaded recursion over structures in modules? How do we know it doesn't run into the same issues auto_debug_signals had?

No. Here we have recursion over `list[Method] | dict[str, Method] | Method`, on the other hand in `auto_debug_signals` we do recursion over fields in classes.

2023-05-13 15:16 UTC, lekcyjna123 commented on test/transactions/test_transaction_lib.py
> +            yield from self.tick(random.randrange(rand) + 1)
Inconsistent fixed.

> Maybe it would be useful if it could be extracted to some mix-in class?

This is good idea, but to implement under different PR, because impact of such changes will be big.

2023-05-13 15:17 UTC, lekcyjna123 commented on test/common.py
> +    @staticmethod
> effectively a classmethod (actual cls instead of SimpleTestCircuit in the body maybe)

Moved as a private function of `elaboratable`.

2023-05-14 08:49 UTC, tilk commented on test/common.py
> +            container: _T_nested_collection[Method],
This function isn't actually called with this type; later in the body, you call it on something of type `Method | list | dict`. And you use it, too: if `container` was really a `_T_nested_collection[Method]`, the `else` would be unreachable, but it isn't and performs a vital function.

2023-05-14 08:54 UTC, lekcyjna123 commented on test/common.py
> +            container: _T_nested_collection[Method],
Yes. It is because Python don't support deep runtime type checking out of the box. It has to by implemented manually and I have done it in this function. But maybe it is wrong idea, and I should create first TypeGuard to do deep check in runtime and first after that call `transform_methods_to_testbenchios`. Such solution will be cleaner.

2023-05-14 09:02 UTC, tilk commented on test/common.py
> +            container: _T_nested_collection[Method],
Or just write the actual type the function works with in the first place and write one or two lines of comments.

2023-05-14 09:14 UTC, tilk commented on test/common.py
> +            container: _T_nested_collection[Method],
This is now cleaner. The `nested_collection` stuff looks potentially useful, maybe it should be moved? Also, the name `_T_nested_collection` should probably be changed, the `_T` prefix should probably be left to TypeVars.

2023-05-14 09:16 UTC, tilk commented on coreblocks/utils/utils.py
> +    def __getattr__(self, name: str) -> Any:
Why `Any`?

2023-05-14 09:18 UTC, lekcyjna123 commented on test/common.py
> +            container: _T_nested_collection[Method],
I thought about that, but as for now we don't have any direct usage for that in other places, so I don't know if this should be moved to coreblock/utils or if this should be a part of utils in tests. So I decided to not move at all and delay this decision till first example of usage in other place will be available, so that no guessing will be needed.

2023-05-14 09:21 UTC, lekcyjna123 commented on coreblocks/utils/utils.py
> +    def __getattr__(self, name: str) -> Any:
Because `HasElaborate` is too weak. It hasn't any information about methods available in elaboratables, so pyright reported errors, even for correct usage. So because of lack of any other ideas how to type that I decided to disable checking of returned types.

2023-05-14 09:25 UTC, tilk commented on coreblocks/transactions/lib.py
> +        @def_method(m, self.read_req, ready=~read_output_valid | self.read_resp.run)
Actually, I don't understand what is happening here, as `read_resp` doesn't set anything combinationally. Where's the dependency?

2023-05-14 09:45 UTC, lekcyjna123 commented on coreblocks/transactions/lib.py
> +        @def_method(m, self.read_req, ready=~read_output_valid | self.read_resp.run)
Dependency is in `self.read_resp.run` in `ready` signal. It is used to as combinational signal to reduce pipeline latency. If there is no valid request currently processed, there is no dependency. Only `read_req` is ready. But when we currently process a request, then we can receive new request only if someone will read old results, so in `read_req` we need to already know if `read_resp` was called or not.

2023-05-14 09:59 UTC, tilk commented on coreblocks/utils/utils.py
> +    def __getattr__(self, name: str) -> Any:
Couldn't you just retain the original, well-typed, references to the modules? Can you point me to the usage site?

If this is not practical, and you add homogenously-typed modules, using generics is one possible solution.

2023-05-14 10:09 UTC, lekcyjna123 commented on coreblocks/utils/utils.py
> +    def __getattr__(self, name: str) -> Any:
One example is in `TestSerializer`. We create `ModuleConnector`, which has `Serializer` instance and two instances of `TestbenchIO`, next we use instance of this module connector to get access to methods which are part of `Serializer.

```py
self.req_method = TestbenchIO(Adapter(i=layout))
self.resp_method = TestbenchIO(Adapter(o=layout))

test_circuit = SimpleTestCircuit(
    Serializer(
        port_count=port_count,
        serialized_req_method=self.req_method.adapter.iface,
        serialized_resp_method=self.resp_method.adapter.iface,
    )
)
m = ModuleConnector(test_circuit=test_circuit, req_method=self.req_method, resp_method=self.resp_method)
```

```py
def requestor(i: int):
    def f():
        for _ in range(test_count):
            d = random.randrange(2**data_width)
            yield from m.test_circuit.serialize_in[i].call(field=d)
            port_data[i].append(d)
            yield from random_wait(requestor_rand)
```

Without `Any`, there is error from pyright that `m.test_circuit` don't have `serialize_in` field.

2023-05-14 11:06 UTC, tilk commented on coreblocks/utils/utils.py
> +    def __getattr__(self, name: str) -> Any:
Why won't you just use `test_circuit` instead of `m.test_circuit` there?

2023-05-14 12:55 UTC, tilk commented on coreblocks/utils/utils.py
> +    def __getattr__(self, name: str) -> Any:
Another take: the `ModuleConnector` was supposed to be a module *combinator*, something that packs a number of modules into one module, to be added into `submodules`. It wasn't supposed to be a module *container*. Note that `submodules` don't work well with this use case, too - it's used to put modules there and that's all, it forgets the types of the modules inside, and this is fine.

If, for some reason, a module *container* will be needed, I'd look into dataclass mixins for that, as this would allow to keep track of types *and* keep the nice constructor syntax of `ModuleConnector`. For now, I recommend removing these two methods.

2023-05-17 09:34 UTC, tilk approved these changes

2023-05-23 15:45 UTC, tilk commented
This PR desperately needs a review!

2023-05-24 15:49 UTC, xThaid commented on coreblocks/transactions/lib.py
> +        @def_method(m, self.read_req, ready=~read_output_valid | self.read_resp.run)
I wasn't clear enough. I still believe that it is possible. The instruction cache works that way -- fully pipelined, 1 cycle latency between request and response and no combinatorial path between the request and response methods.

So basically it works by employing one FIFO of depth 2 and one forwarder. After the request method is called, we put the request to the FIFO and at the same time we query the memory. In the next cycle, we read the response from the memory and put it in the forwarder. In the response method we read both Forwarder and FIFO. The FIFO basically works as a rate-limiter (because we don't care about it contents, but only about the number of elements), so a simplified version can be used (something like a semahore)

2023-05-24 15:50 UTC, xThaid commented on test/transactions/test_transaction_lib.py
> +                # print("w", a, d)
The comments here and below can be probably removed.

2023-05-24 15:51 UTC, xThaid commented on test/transactions/test_transaction_lib.py
> +class TestMemoryBank(TestCaseWithSimulator):
The test doesn't test if the memory bank is pipelined.

2023-05-31 19:51 UTC, tilk commented on coreblocks/transactions/lib.py
> +        @def_method(m, self.read_req, ready=~read_output_valid | self.read_resp.run)
This worries me a little, as (if I understand you correctly) your current implementation reorders reads with respect to writes. This can possibly reduce the usefulness of this module. Did you really intend this to happen?

2023-06-01 12:35 UTC, tilk commented on coreblocks/transactions/lib.py
> +        @def_method(m, self.read_req, ready=~read_output_valid | self.read_resp.run)
I've read your code, and I'm now certain that your code doesn't reorder reads and writes - *your test does*. Don't mess with the internals (you really like that, don't you?) and fix the test.

2023-06-01 12:39 UTC, tilk requested changes
The test for `MemoryBank` improperly models reads and writes, which somehow lead you to hack up the test to make it pass. Fix the test, please.

2023-06-01 12:57 UTC, tilk commented on coreblocks/transactions/lib.py
> +
Oh, but this code *doesn't* run always! This runs only when the forwarder is ready, which can make you miss the cycle when the results are available.

2023-06-02 19:00 UTC, Arusekk commented on test/common.py
> +        return all([guard_nested_collection(elem, t) for elem in cont.values()])
Not sure if we want Yet Another Dict Tree Traversal... I kind of think this can also be done in a tiny bit more generic way, like:
```suggestion
    if isinstance(cont, (list, dict)):
        if isinstance(cont, dict):
            cont = cont.values()
        return all([guard_nested_collection(elem, t) for elem in cont])
```

we should just do one generic version of it, and pass a callback/aggregator function along.

2023-06-02 19:00 UTC, Arusekk commented on test/common.py
> +        def transform_methods_to_testbenchios(
Yet Another Dict Tree Traversal.  Do we really need it?

2023-06-02 21:15 UTC, tilk commented on coreblocks/transactions/lib.py
> +                ("mask", self.width // self.granularity),
I think I also prefer the `append` approach; it makes it *more* explicit that the rest of the fields are the same in both cases.

2023-06-03 02:03 UTC, xThaid commented on coreblocks/transactions/lib.py
> +        @def_method(m, self.read_req, ready=~read_output_valid | self.read_resp.run)
Instead of decreasing the size of the semaphore, we could increase the size of the forwarder (I know that our forwarder right now has a constant size, but right now I can't find a reason why Forwarder wouldn't have arbitrary size).

Another solution (the one I used in the cache module) is that we can just buffer (let's call it **B**) the latest request and if the method `request` is called, we read the memory using the argument of the method, if it is not, we use **B** to read the memory. That way, if we have two consecutive reads, the first read's response will be buffered in the forwarder and the second read address will be sitting in the buffer.

2023-06-04 11:32 UTC, lekcyjna123 commented on test/common.py
> +        return all([guard_nested_collection(elem, t) for elem in cont.values()])
> we should just do one generic version of it, and pass a callback/aggregator function along.

As for now we don't have dict/list tree traversal in any other place, so i decided to don't make it separate function as for now. In future if this will be needed, it can be done separate.

2023-06-04 11:33 UTC, lekcyjna123 commented on test/common.py
> +        def transform_methods_to_testbenchios(
If you have an idea for to realise this transformation in other way I am happy to hear you.

2023-06-04 11:34 UTC, lekcyjna123 commented on coreblocks/transactions/lib.py
> +
As explained on meeting this will work correctly.

2023-06-05 08:32 UTC, tilk commented
Did you stop using a LLM for grammar fixes? Would approve, but the docstrings are atrocious.

2023-06-05 08:41 UTC, tilk commented on coreblocks/transactions/lib.py
> +            self.read_req.schedule_before(self.write)
Is this needed?

2023-06-05 17:52 UTC, tilk commented on coreblocks/transactions/lib.py
> +            self.read_req.schedule_before(self.write)
Or let's state it another way. There is some combinational dependence between method bodies. But does it influence scheduling?

2023-06-17 18:23 UTC, Arusekk approved these changes

2023-06-23 13:30 UTC, lekcyjna123 commented on coreblocks/transactions/lib.py
> +            self.read_req.schedule_before(self.write)
It turns out that, this dependence is not needed. It have been removed.

2023-06-27 13:09 UTC, merged