[WIP] Simultaneous transactions
kuznia-rdzeni/coreblocks pull request #347
Opened 2023-05-18 18:02 UTC by tilk

This is a proposal to extend the transaction system with simultaneity relations, which enforce that selected transactions/methods always run together in the same clock cycle. This is realized by "gluing" the simultaneous transactions into larger ones.

Two features are added to the library, hopefully encapsulating some typical use cases:

* `Connect`, which is kind of like `ConnectTrans`, but gender-reversed. `ConnectTrans` takes two methods and executes them together, with bidirectional data exchange. `Connect`, on the other hand, presents two methods, which always execute together and exchange data bidirectionally. It's kinda like `Forwarder`, but without the buffer and with a reverse channel.
* `condition`, which allows to build `If`-like statements inside transaction or method bodies, which, in contrast to typical `If`, can have different sets of methods called, and the methods not called are not blocked. The usefulness of this construction requires exploration.

This is a prototype, hopefully useful for solving some design challenges in our core. Comments are appreciated.

Depends on #337, #345 and #346.

2023-05-21 08:41 UTC, lekcyjna123 commented on coreblocks/transactions/lib.py
> +            m.d.av_comb += read_value.eq(arg)
Why `av_comb` and not an `top_comb`?

2023-05-21 08:41 UTC, lekcyjna123 commented on coreblocks/transactions/lib.py
> +            pass
What if user will add default branch in his code and mark `nonblocking=True`? If I correctly understand code, this will be an error.

2023-05-21 11:11 UTC, tilk commented on coreblocks/transactions/lib.py
> +            m.d.av_comb += read_value.eq(arg)
In this situation they are equivalent (as there are no further conditions here). Do you think that we should have some rules for using the additional domains? Like e.g. prefer `top_comb`, if you need conditions use `av_comb`, if you use signals across methods/transactions use `comb`.

2023-05-21 11:12 UTC, tilk commented on coreblocks/transactions/lib.py
> +            pass
See line 833. If the user adds a default branch, the implicit default branch will not be added. (Yeah, mutating function arguments is confusing, maybe a separate variable should be added for that?)

2023-06-04 10:35 UTC, lekcyjna123 requested changes
Overall looks good, but I have found one corner case which should be fixed before merge.

2023-06-04 10:35 UTC, lekcyjna123 commented on test/transactions/test_simultaneous.py
> +class ConditionTestCircuit(Elaboratable):
This should be moved in my opinion to test_transaction_lib.py, because `condition` is defined in `transactions/lib.py`

2023-06-05 07:34 UTC, tilk commented on coreblocks/transactions/core.py
> +        others[0].independent(*others[1:])
Independence is not transitive, but the relation you mention is implicit. Each call of `independent` defines a set for which each pair is considered independent. For example, `a.independent(b,c)` means that each of `(a, b)`, `(a, c)`, `(b, c)` are independent.

2023-06-05 09:54 UTC, tilk commented on coreblocks/transactions/core.py
> +        while q:
No. If this is unsatisfiable, `condition` should be unsatisfiable, too. Could you describe how you came upon this graph? What did you intend to do?

2023-06-05 15:25 UTC, lekcyjna123 commented on coreblocks/transactions/core.py
> +        while q:
I don't have intend to do anything like that. I simply read the code and such example came to my mind. I see now that in such case `condition` will be unsatisfiable too. But this left me wonder what is the exact semantic of `independent`? This is not a simple reverse of `simultaneus` because it can influence transitivity of `simultaneus`.

2023-06-05 15:26 UTC, lekcyjna123 approved these changes

2023-06-05 16:19 UTC, tilk commented on coreblocks/transactions/core.py
> +        while q:
Its whole function is to influence the transitivity computation, so that the things that can't be simultaneous, are not. But I wouldn't recommend using `independent` in user code - exactly because its semantics is (currently?) sketchy, and it's possible it will disappear completely from future iterations. (I think that, for this reason, `independent` should probably be marked as internal.) But on the upside, the simple (but possibly troublesome) model used now was successfully used to validate the implementation mechanics of simultaneous transactions, and they seem fine.

2023-06-19 11:13 UTC, piotro888 approved these changes
Looks good from what I understand

2023-06-22 18:56 UTC, merged