ZBB extension
kuznia-rdzeni/coreblocks pull request #369
Opened 2023-05-29 16:15 UTC by wojpok

2023-05-30 09:43 UTC, piotro888 commented on coreblocks/fu/alu.py
> +        self.zba_enable = alu_fn.zba_enable
did you mean
```suggestion
        self.zbb_enable = alu_fn.zbb_enable
```
?

2023-05-30 09:43 UTC, piotro888 commented on coreblocks/fu/alu.py
> +            if self.zba_enable:
also here

2023-05-30 11:57 UTC, wojpok commented on coreblocks/fu/alu.py
> +        self.zba_enable = alu_fn.zba_enable
Yup, my bad

2023-05-31 10:35 UTC, lekcyjna123 commented on coreblocks/params/isa.py
> +    ROL = ROR = SEXTB = SEXTH = 0b0110000
Why you define sextb and sexth both in Func7 and Funct12?

2023-05-31 10:35 UTC, lekcyjna123 commented on coreblocks/params/isa.py
> +    CPOP = CLZ = CTZ = 0b0011000
This CTZ is wrong

2023-05-31 10:52 UTC, wojpok commented on coreblocks/params/isa.py
> +    ROL = ROR = SEXTB = SEXTH = 0b0110000
It's necessary in order to decode instruction in alu decoder. I cant use use funct12 there

I guess I could add a function that extracts funct7 from funct12 and remove all redundant funct7 definitions, but I am not sure which solution is better

2023-05-31 11:43 UTC, tilk commented on coreblocks/params/isa.py
> +    CPOP = CLZ = CTZ = 0b0011000
You mean, it should be 0110000, right? (You could write that yourself.)

2023-05-31 12:54 UTC, lekcyjna123 commented on coreblocks/fu/alu.py
> +                    def iter(step: int, s: Value) -> Value:
What is your invariant ins this function? I don't see how this function works. If I would like to get count of leading zeros of 2-bits signal, then I should pass as a step `0` (because line 185 give us `log2(2)-1 = 0`). In result I expected 2 bits result (0 - leading zeros, 1 - leading zero or two leading zeros). But If I correctly see `iter(-1)` will return 1-bit signals, `le` will be 1, so length of `high_bits` will be 1. So both `resh` and `resl` will have 1 bit length so result also will be 1 bit.

I am right? Or have I do an error in my calculations?

2023-05-31 14:29 UTC, lekcyjna123 commented on test/params/test_configurations.py
> +        ISAStrTest(
Adding this exetension to `docker/riscv-toolchain.Dockerfile` isn't needed?

2023-05-31 15:46 UTC, tilk commented on coreblocks/fu/alu.py
> +                    def iter(step: int, s: Value) -> Value:
As an aside, I think that the clz/ctz functions should be defined outside ALU, like e.g. popcount.

2023-06-02 17:25 UTC, piotro888 requested changes

2023-06-02 17:25 UTC, piotro888 commented on coreblocks/frontend/decoder.py
> +        Encoding(Opcode.OP_IMM, Funct3.ORCB, funct12=Funct12.ORCB),
This will not work without changes in decoder.
Please add test case to `test_decoder` with example ZBB instruction.

Funct12 is not selected for OpType matching because `OP_IMM` format -> `IntstrType.I` doesn't support Funct12 matching.
It is currently only manually enabled to `SYSTEM;PRIV` instuction with this line  `m.d.comb += self.funct12_v.eq((opcode == Opcode.SYSTEM) & (self.funct3 == Funct3.PRIV))`
Temporary solution could be to add OP_IMM with all of ZBB Fuct3 fields to that line, but for longer term decoding method really needs a refactor...

2023-06-03 07:31 UTC, wojpok commented on coreblocks/params/isa.py
> +    CPOP = CLZ = CTZ = 0b0011000
Yikes, I need to introduce 3 new optypes to solve this

2023-06-04 08:06 UTC, lekcyjna123 commented on coreblocks/utils/utils.py
> +    # this swith negates this effect
```suggestion
    # this switch negates this effect
```

2023-06-04 08:06 UTC, lekcyjna123 commented on test/utils/test_utils.py
> +        self.test_number = 40
You will check combinational circuit many times with the same arguments for some size (e.g. size=1), so maybe it will be better to make exhaustive check?

2023-06-05 07:45 UTC, tilk commented on coreblocks/utils/utils.py
> +    # solution is a mirrored version of CLZs
Amaranth `Value` supports slicing. How about `sig[::-1]`?

2023-06-05 07:50 UTC, tilk commented on coreblocks/utils/utils.py
> +        result = (upper_mask & upper_value) | (lower_mask & (current_bit | lower_value))
Isn't this just a hand-written multiplexer, and therefore `Mux` could be used?

2023-06-05 08:10 UTC, tilk commented on coreblocks/utils/utils.py
> +    # solution is a mirrored version of CLZs
This function looks simpler (no `upper_bound`). So maybe keep ctz as the main implementation, and calculate clz using ctz?

To think about (as this is an optimization): one could use either clz and ctz in the ALU (as it is now), or just use one of them (ctz?), and calculate the other using the same circuit and bit reversal. The second implementation will be better in terms of resource usage, and probably shouldn't hurt fmax.

2023-06-05 08:11 UTC, tilk commented on coreblocks/utils/utils.py
> +def count_leading_zeros(s: Value, xlen_log: int) -> Value:
I think this function should be simple to adapt to work with any bit widths, not only powers of 2; and at the same time, the edge case could be eliminated. Just concatenate a 1 to act as a guard, and don't recurse on empty range. (This will probably be easier to implement on ctz?)

2023-06-05 08:14 UTC, tilk commented on test/utils/test_utils.py
> +        self.test_number = 40
But this will increase the code complexity for no good reason.

2023-06-07 16:11 UTC, lekcyjna123 approved these changes

2023-06-10 13:33 UTC, piotro888 commented on coreblocks/utils/utils.py
> +    xlen_log = int(xlen_log)
Conversion to int is no longer needed

2023-06-10 13:33 UTC, piotro888 commented on coreblocks/fu/alu.py
> +        self.zba_enable = zbb_enable
```suggestion
        self.zbb_enable = zbb_enable
```

2023-06-11 18:45 UTC, piotro888 approved these changes

2023-06-12 08:55 UTC, merged