Encoding uniqueness
kuznia-rdzeni/coreblocks pull request #388
Opened 2023-06-12 10:33 UTC by wojpok

An additional check that verifies whether all encodings are unique

2023-06-13 11:01 UTC, Kristopher38 requested changes

2023-06-13 11:01 UTC, Kristopher38 commented on test/frontend/test_decoder.py
> +            for instruction in _instructions_by_optype[ext]:
One loop instead of two nested ones will suffice:
```Python
for ext, instruction in _instructions_by_optype.items():
```

2023-06-13 11:22 UTC, tilk commented on test/frontend/test_decoder.py
> +            for instruction in _instructions_by_optype[ext]:
...are you sure? Because `_instructions_by_optype` is a dict of lists, and he intends to iterate over the elements of the lists.

2023-06-13 11:28 UTC, tilk commented on test/frontend/test_decoder.py
> +            for instruction in _instructions_by_optype[ext]:
One could avoid nested loops by using `itertools.chain`, but then the semantics of the check would change: currently this code checks uniqueness per extension, not across all extensions. (Is this the right thing? Are extensions permitted to have collisions on instruction encodings?)

2023-06-13 11:31 UTC, tilk commented on test/frontend/test_decoder.py
> +            funct7 = int(instr.funct7) if instr.funct7 is not None else funct7_of_funct12(instr.funct12)
How would the match statement help, other than increasing verbosity?

2023-06-13 11:33 UTC, wojpok commented on test/frontend/test_decoder.py
> +            for instruction in _instructions_by_optype[ext]:
Code was meant to check whether there are no collisions within OpType and all the unary operations from ZBB are distinguishable but I guess the functionality could be extended

2023-06-13 11:37 UTC, tilk commented on test/frontend/test_decoder.py
> +                )
This does not really do the job. If a given field (`funct3` etc.) on the `Encoding` is `None`, this means that it does not matter (works as a wildcard). You don't check for that here, failing to detect some possible collisions. Also, mapping `None` to 0, as you are currently doing, is wrong: 0 is a valid value for `funct3` etc.

2023-06-13 11:56 UTC, wojpok commented on test/frontend/test_decoder.py
> +                )
So changing ints in tuples to optional ints will work or do I need to implement different approach?

2023-06-13 12:05 UTC, tilk commented on test/frontend/test_decoder.py
> +                )
No, it will not. For example, `Encoding(Opcode.OP, Funct3.ADD, Funct7.SUB)` collides with `Encoding(Opcode.OP, Funct3.ADD)` (a purposely wrong encoding), but this approach will not detect this.

2023-06-13 12:23 UTC, Kristopher38 commented on test/frontend/test_decoder.py
> +            funct7 = int(instr.funct7) if instr.funct7 is not None else funct7_of_funct12(instr.funct12)
it might be just my personal preference then, seeing a lot of checks for `None` done with ifs (esp. nested ones like is done here) triggers some defense mechanism in my brain

2023-06-13 12:28 UTC, Kristopher38 commented on test/frontend/test_decoder.py
> +            for instruction in _instructions_by_optype[ext]:
ah nvm, still needs 2 nested loops but this is more pythonic:
```Python
for ext, instructions in _instructions_by_optype.items():
    for instruction in instructions:
```

2023-06-13 12:29 UTC, tilk commented on test/frontend/test_decoder.py
> +            funct7 = int(instr.funct7) if instr.funct7 is not None else funct7_of_funct12(instr.funct12)
> seeing a lot of checks for None done with ifs (esp. nested ones like is done here) triggers some defense mechanism in my brain

It's a pretty good defense mechanism, actually, as nonchalant use of optional values (especially in untyped contexts) tends to lead to "fun" bugs.

2023-06-14 10:18 UTC, wojpok commented on test/frontend/test_decoder.py
> +                )
So I added a test that verifies uniqueness globally and found out that I made mistake while adding ZBB instructions to decoder

2023-06-15 05:58 UTC, lekcyjna123 approved these changes

2023-06-15 09:09 UTC, piotro888 requested changes

2023-06-15 09:09 UTC, piotro888 commented on test/frontend/test_decoder.py
> +                known_codes: set[code_type] = set()
Shouldn't this set be declared one line above? It is created new for each instruction.

And after that change, this test fails for ex. sll & slli, because we actually don't distinguish between them in core as instructions. We only look if immediate is present and then mux it as the second parameter instead of 0 register and treat it as OP variant (and this is working for all OP_IMM instructions).

The same is true for add and addi, but it is not detected, because of `instr.funct7 is not None else None` and in real core if fuct7 is not defined it is set to 0 and FU decoding **depends** on it to treat addi(op=OP_IMM, f3=ADD) exactly like add(op=OP_IMM, f3=ADD, f7=ADD(**=0**)).

To fix that we would need to check for imm as additional uniqueness factor in this check (because it alters the instrucion execution in that cases). But that complicates things a lot, decoder doesn't even check for imm field validity (FU just takes it if rs2=0. If rs2 is meant to be a valid 0, then imm should be 0 as well) (edit: decoder sets imm to 0 if instruciton type is R, in other cases it is filled, maybe we could just check for R/not R instruction type?)

2023-06-16 15:35 UTC, piotro888 approved these changes

2023-06-26 09:24 UTC, Kristopher38 approved these changes

2023-06-26 09:40 UTC, merged