Division unit
kuznia-rdzeni/coreblocks pull request #389
Opened 2023-06-13 11:52 UTC by wojpok

Simple implementation of long division using method described [here](https://yuhei1-horibe.medium.com/designing-divider-213fbd32beb2).

Currently module is hard coded to calculate everything in 4 cycles, but more flexible design will be implemented later.
Signed operation will be added later as well.

2023-06-17 17:25 UTC, tilk commented
You could enable division tests in `scripts/run_tests.sh`.

2023-06-17 18:01 UTC, tilk commented
And boom, test failed. The failing one is:

```
TEST_RR_OP( 8, div, -1, -1<<31, 0 );
```

2023-06-17 18:35 UTC, wojpok commented
There is really weird edge case with the fact that -INT32_MIN == INT32_MIN. I'll fix this tomorrow

2023-06-18 16:55 UTC, pa000 commented on coreblocks/fu/div_unit.py
> +            result_fifo.write(m, rob_id=params.rob_id, result=sign_result, rp_dst=params.rp_dst)
I would move the body of this transaction directly into the `accept` method. This makes it slightly more readable and allows you to get rid of `result_fifo`.

2023-06-18 16:55 UTC, pa000 commented on coreblocks/fu/div_unit.py
> +            rem_res = Signal(1)  # flag wheather we want result or reminder
```suggestion
            rem_res = Signal(1)  # flag whether we want result or reminder
```

2023-06-18 16:55 UTC, pa000 commented on coreblocks/fu/divison/long_division.py
> +        self.n = count
`self.count` would be a more consistent name. Or maybe even `step_count`.

2023-06-18 16:55 UTC, pa000 commented on coreblocks/fu/divison/long_division.py
> +        # reseting
```suggestion
        # resetting
```

2023-06-18 16:55 UTC, pa000 commented on coreblocks/fu/divison/long_division.py
> +            # so in each iterations upper bits are fed into recursive divider
```suggestion
            # so in each iteration upper bits are fed into recursive divider
```

2023-06-18 16:55 UTC, pa000 commented on coreblocks/fu/divison/long_division.py
> +            # if we are in the last stage and uneven amaount of bits needs to be handled
```suggestion
            # if we are in the last stage and uneven amount of bits needs to be handled
```

2023-06-18 16:55 UTC, pa000 commented on coreblocks/fu/divison/long_division.py
> +Alogorithm - multi-cycle array divider
```suggestion
Algorithm - multi-cycle array divider
```

2023-06-18 16:55 UTC, pa000 commented on coreblocks/fu/divison/long_division.py
> +        # Signle step as described in article
```suggestion
        # Single step as described in article
```

2023-06-18 23:44 UTC, Kristopher38 commented on coreblocks/fu/div_unit.py
> +            rem_res = Signal(1)  # flag wheather we want result or reminder
Even
```suggestion
            rem_res = Signal(1)  # flag whether we want result or remainder
```
;)

2023-06-19 11:26 UTC, wojpok commented on coreblocks/fu/div_unit.py
> +            result_fifo.write(m, rob_id=params.rob_id, result=sign_result, rp_dst=params.rp_dst)
Currently module follows same structure as multiplication unit and I'm honestly not sure which version would better in the long run

2023-06-23 11:40 UTC, lekcyjna123 requested changes
I suppose that `docker/riscv-toolchain.Dockerfile` also should be updated.

2023-06-23 11:40 UTC, lekcyjna123 commented on coreblocks/fu/divison/long_division.py
> +        with m.If(~ready & (stage < self.stages)):
Maybe use `stage != self.stages`? This should be cheaper in HW.

2023-06-26 09:43 UTC, tilk commented
> I suppose that `docker/riscv-toolchain.Dockerfile` also should be updated.

I don't think this should be a requirement for this PR.

2023-06-27 10:34 UTC, lekcyjna123 commented
> Extending Docker could be done in seperate PR alongside with enabling ZBS and ZBC FUs because full config is in fact not a full config

Ok. But please answer rest of my comments.

2023-06-30 07:31 UTC, lekcyjna123 approved these changes

2023-06-30 20:53 UTC, tilk commented
I've run the synthesis benchmark (https://github.com/kuznia-rdzeni/coreblocks/actions/runs/5425431940/jobs/9866166080), and it looks like this PR reduces the Fmax to 38.4 MHz. It might be worthwhile to check if reducing "ipc" helps.

2023-06-30 21:00 UTC, tilk commented on coreblocks/fu/divison/long_division.py
> +        self.partial_reminder = Signal(unsigned(size))
```suggestion
        self.partial_remainder = Signal(unsigned(size))
```

2023-06-30 21:05 UTC, tilk commented on coreblocks/fu/divison/long_division.py
> +        @def_method(m, self.clear)
Needs to be last, otherwise, when `issue` is run concurrently with `clear`, `issue` will "win". (Clears are not really tested anywhere yet, but we are doing them in preparation for interrupts.)

2023-06-30 21:07 UTC, tilk commented on coreblocks/fu/divison/long_division.py
> +            m.d.sync += quotient.eq(0)
Not really needed, these are not used for ready signals and are cleared on issue.

2023-07-03 09:37 UTC, tilk approved these changes

2023-07-03 09:38 UTC, merged