Update synthesis docs
kuznia-rdzeni/coreblocks pull request #454
Opened 2023-07-27 14:48 UTC by lekcyjna123

I have found today that our synthesis page in documentation is a little bit out-of-date, so I updated it by adding information how to use our pre-build docker image.

2023-07-28 08:46 UTC, tilk commented
Please, check the grammar first before submitting any English text in a PR.

2023-11-14 19:00 UTC, tilk commented on docs/synthesis/Synthesis.md
> +### Using pre-build container
```suggestion
### Using pre-built container
```

2023-11-14 19:01 UTC, tilk commented on docs/synthesis/Synthesis.md
> +In order to perform synthesis without using the ready container you will need to install following tools:
What is the "ready container"?

2023-11-14 19:02 UTC, tilk commented on docs/synthesis/Synthesis.md
> +- IPC
This is nonsense. IPC is calculated from simulation, not synthesis.

2023-11-15 21:09 UTC, Kristopher38 requested changes

2023-11-15 21:09 UTC, Kristopher38 commented on docs/synthesis/Synthesis.md
> +pip3 install -r requirements-dev.txt
Just a sanity check - did you test that these commands actually work? The docker image is using ubuntu 23.04 and I have a suspicion that this line will fail due to `pip` not liking that you want to install packages globally (even if it's in docker) and that you should use a virtualenv (adding `python3 -m venv venv && source venv/bin/activate` would help)

2023-11-18 18:06 UTC, lekcyjna123 commented on docs/synthesis/Synthesis.md
> +pip3 install -r requirements-dev.txt
I checked that commands worked when I submitted this PR for the first time, so in June. I will check that once more time.

2023-11-19 11:31 UTC, lekcyjna123 commented on docs/synthesis/Synthesis.md
> +- IPC
Fixed by extension of the whole document.

2023-11-19 12:35 UTC, tilk requested changes

2023-11-19 12:35 UTC, tilk commented on docs/synthesis/Synthesis.md
> +the configuration provided by the user and then passes it to the Amaranth to generate a Verilog description from that instance.
```suggestion
the configuration provided by the user and then passes it to Amaranth to generate a Verilog description from that instance.
```

2023-11-19 12:35 UTC, tilk commented on docs/synthesis/Synthesis.md
> +This description is then processed by the Yosys and nextpnr-ecp5 to generate the ECP5 bitstream.
```suggestion
This description is then processed by Yosys and nextpnr-ecp5 to generate the ECP5 bitstream.
```

2023-11-19 12:35 UTC, tilk commented on docs/synthesis/Synthesis.md
> +The strength of the Coreblocks is its modularity, so we can provide different configurations with little effort. You can choose
```suggestion
A strength of Coreblocks is its modularity, so we can provide different configurations with little effort. You can choose
```

2023-11-19 12:35 UTC, tilk commented on docs/synthesis/Synthesis.md
> +  * [prjtrellis](https://github.com/YosysHQ/prjtrellis) - provides the description of the ECP5 bitstream format
```suggestion
  * [yosys](https://github.com/YosysHQ/yosys) - to synthesise the Verilog generated by Amaranth up to gate level;
  * [nextpnr-ecp5](https://github.com/YosysHQ/nextpnr.git) - to perform the "Place and Route" step;
  * [prjtrellis](https://github.com/YosysHQ/prjtrellis) - provides the description of the ECP5 bitstream format.
```

2023-11-19 12:35 UTC, tilk commented on docs/synthesis/Synthesis.md
> +of instructions executed per clock cycle (IPC). This is done by simulating the core with cycle accuracy and running
The IPC measure depends not only on the latency in various parts of the core, but on many other factors. Notice that there are pipeline designs with long latency, but high throughput (which is what IPC actually measures). This introduction is very misleading.

2023-11-19 12:35 UTC, tilk commented on docs/synthesis/Synthesis.md
> +simulated core. The compilation is done using [riscv-gnu-toolchain](https://github.com/riscv/riscv-gnu-toolchain), with
```suggestion
the simulated core. The compilation is done using [riscv-gnu-toolchain](https://github.com/riscv/riscv-gnu-toolchain), with
```

2023-11-19 14:24 UTC, lekcyjna123 commented on docs/synthesis/Synthesis.md
> +of instructions executed per clock cycle (IPC). This is done by simulating the core with cycle accuracy and running
Added note about throughput.

2023-11-19 14:24 UTC, lekcyjna123 commented on docs/synthesis/Synthesis.md
> +## Benchmarking
Uploaded a next version.

2023-11-19 14:24 UTC, lekcyjna123 commented on docs/synthesis/Synthesis.md
> +RISC-V extensions or the embench isn't be updated.
Removed

2023-11-19 14:25 UTC, lekcyjna123 commented on docs/synthesis/Synthesis.md
> +PYTHONHASHSEED=0 ./scripts/synthesize.py --verbose --config <your_config>
Updated

2023-11-27 09:33 UTC, tilk reviewed
Almost here.

2023-11-27 09:33 UTC, tilk commented on docs/synthesis/Synthesis.md
> +Regression tests should ensure that Coreblocks is complaint with RISC-V specification requirements. Tests include
!!!
```suggestion
Regression tests should ensure that Coreblocks is compliant with RISC-V specification requirements. Tests include 
```

2023-11-27 09:33 UTC, tilk commented on docs/synthesis/Synthesis.md
> +sudo docker pull ghcr.io/kuznia-rdzeni/riscv-toolchain:2023.10.08_v
I suggest having a `latest` tag to avoid updating this doc on every docker change. This needs to be changed on other lines too.
```suggestion
sudo docker pull ghcr.io/kuznia-rdzeni/riscv-toolchain:latest
```

2023-12-03 18:41 UTC, lekcyjna123 commented on docs/synthesis/Synthesis.md
> +sudo docker pull ghcr.io/kuznia-rdzeni/riscv-toolchain:2023.10.08_v
But we don't use the tag `latest`. 
```sh
sudo docker pull ghcr.io/kuznia-rdzeni/riscv-toolchain:latest
```
That command doesn't work.

2023-12-03 18:47 UTC, tilk commented on docs/synthesis/Synthesis.md
> +sudo docker pull ghcr.io/kuznia-rdzeni/riscv-toolchain:2023.10.08_v
No, we don't. Maybe we should? (That was the suggestion.)

2023-12-03 18:54 UTC, lekcyjna123 commented on docs/synthesis/Synthesis.md
> +sudo docker pull ghcr.io/kuznia-rdzeni/riscv-toolchain:2023.10.08_v
Maybe we should have two sets of tags? One to use in pipelines to allow easy tracking of changes and second tag `latest` for the documentation? Or maybe we should use only the `latest` tag and use checksums in pipelines?

I don't want to use `latest` in pipelines, because that will cause some tricky errors (e.g. updating dockers in preparation for Dockerfile change, while some other review is being tested).

2023-12-03 21:08 UTC, tilk approved these changes

2023-12-17 22:03 UTC, Durchbruchswagen approved these changes

2023-12-18 09:53 UTC, merged