Fix zbs and DecoderManager docstrings
kuznia-rdzeni/coreblocks pull request #470
Opened 2023-10-07 12:58 UTC by lekcyjna123

Sphinx raised a warning about zbs unit docstrings and the docs were generated wrongly. Additionally docstrings for `DecoderManager` were miss placed, so they weren't included in API output.

This commit fix both issues.

2023-10-07 15:07 UTC, tilk commented on coreblocks/fu/fu_decoder.py
> +        Method providing list of valid instruction.
Don't we usually start the first line immediately after the triple quote?

2023-10-07 15:18 UTC, tilk approved these changes

2023-10-30 14:50 UTC, JumiDeluxe requested changes
Builds for me.
Just missing `Fn: Type[IntFlag]` in generated Sphinx documentation, with suggested changes everything is OK

2023-10-30 14:50 UTC, JumiDeluxe commented on coreblocks/fu/fu_decoder.py
>      Fn: Type[IntFlag]
Sphinx doesn't generate documentation for this variable when it's comment block is placed above it.

Move it below. Then it generates documentation from the comment.

```suggestion
    """
    Type[IntFlag]

    Enumeration of instructions implemented in given functional unit.
    """
    Fn: Type[IntFlag]
```

2023-10-30 14:50 UTC, JumiDeluxe commented on coreblocks/fu/fu_decoder.py
>      Fn: Type[IntFlag]
I think that `Type[IntFlag]` in comment blocks is not even needed since we have type hint.
Just 
```python
Fn: Type[IntFlag]
    """Enumeration of instructions implemented in given functional unit."""
```
should be enough (works for me).

2023-11-05 20:04 UTC, JumiDeluxe approved these changes

2023-11-05 20:29 UTC, merged