Implement physical memory attributes (PMA) for memory-mapped IO (MMIO)
kuznia-rdzeni/coreblocks pull request #510
Opened 2023-11-12 23:23 UTC by kindlermikolaj

DRAFT: 
This PR adds basic physical memory attributes implementation, currently with only one attribute (MMIO, that should be defined in core configuration). PMAChecker(Elaboratable)  with method `ask` is used to fetch all attributes for given memory address.

2023-11-13 11:17 UTC, tilk commented on coreblocks/lsu/dummyLsu.py
> +            with m.State("Load"):
The additional cycle increases latency and decreases throughput. PMAs should work purely combinationally (and they do!) and not introduce any delay cycles.

2023-11-13 14:17 UTC, tilk commented on coreblocks/params/configurations.py
> +    mmio : [(int,, int)]
Suggestion: `[PMARegion]`, where `PMARegion` is a dataclass with three fields: `start`, `end` and `mmio`.

2023-11-13 14:20 UTC, tilk commented on coreblocks/lsu/pma.py
> +            out_signals = dict()
For each region, check if `addr` is in the region, if it is, output value for the region is taken from PMAs, if not, zero. At the end, "or" everything.

2023-11-13 14:31 UTC, tilk commented on coreblocks/lsu/dummyLsu.py
> +            with m.State("Load"):
Maybe use nested transactions?

2023-11-15 13:32 UTC, tilk commented on coreblocks/lsu/dummyLsu.py
> +            with m.State("Load"):
Disregard the previous comment, see new DummyLSU in #511.

2023-11-18 13:31 UTC, kindlermikolaj commented on coreblocks/lsu/dummyLsu.py
> +            with m.State("Load"):
Ok, I think that the best solution is to check PMAs during insert. Then, only LSUDummy needs to have access to PMAChecker. MMIO flag should be part of `current_instr` record, since it is required for every instruction.

2023-11-18 14:01 UTC, tilk commented
The refactored LSU is now in master. I think it's better for you to stop working on the outdated code and rebase to master ASAP.

2023-11-18 14:34 UTC, tilk commented on coreblocks/lsu/pma.py
> +        self.attrs["mmio"] = PhysMemAttr(gen_params)
Why are you insisting on mangaging ranges per attribute instead of attributes per range? It's not that each attribute will have completely different set of ranges, a typical situation is that different ranges differ on a lot of attributes.

2023-11-18 14:45 UTC, kindlermikolaj commented on coreblocks/lsu/pma.py
> +        self.attrs["mmio"] = PhysMemAttr(gen_params)
I'm not insisting on it, I just did PMARegion, refactoring PMAChecker is next on list.

2023-11-18 17:50 UTC, tilk commented on coreblocks/lsu/pma.py
> +    def merge_intervals(acc: tuple[tuple[int, int], list], el: tuple[int, int]):
There is no need to do any merging. You can assume here that the input data is correct and don't worry about optimality. If in doubt, keep things simple.

2023-11-18 23:26 UTC, kindlermikolaj commented on coreblocks/lsu/pma.py
> +    def merge_intervals(acc: tuple[tuple[int, int], list], el: tuple[int, int]):
Done

2023-11-19 00:00 UTC, kindlermikolaj commented
One issue I arrived at:
Unless there is a way to assert that method is not ready, it is currently impossible to test if PMAs work because such test would freeze. One solution would be to add a function to AdapterTrans that returns readiness status of method.

2023-11-19 12:42 UTC, Kristopher38 commented
There's a `call_try` method in the adapter that will call the method if it's ready (and return it's returned data) or return None (iirc) if it's not ready.

2023-11-19 14:39 UTC, piotro888 requested changes

2023-11-19 14:39 UTC, piotro888 commented on coreblocks/params/configurations.py
> +        Ranges of memory mapped input output.
Update the docstring

2023-11-19 14:39 UTC, piotro888 commented on coreblocks/lsu/pma.py
> +    attrs: Record
I think that using single fields like `mmio` of type `Bool` fits better here.
It allows to document each field here, specify default values and the configuration is cleaner.
`Record` could be constructed in elaboratable.

2023-11-19 14:39 UTC, piotro888 commented on coreblocks/lsu/dummyLsu.py
> +                m.d.sync += current_instr.mmio.eq(mmio_flag)
This won't work here. You use `current_instr.s1_val` in `calculate_addr`, but at this stage this field may not be valid here.

In FUs (RSes) `insert` is called first for each instruction, and register values may be already computed or not. If register value is not yet known, it will be supplied later via `update` call. See `instr_ready` definition.

You need to check that after `instr_valid` is set. Which can be only after `insert` or `insert`+`update`.

Proposed solutions:
1) Move this transaction one level up (not under any method), with run condition of `instr_ready`. The result signal should be updated both in comb domain to affect issue condtion, which also depends on instr_ready. Because of combinational dependency your transaction must be `scheduled_before` the `issue` transaction.
2) Execute `pma.ask` always under `issue` transaction, and execute rest of the code there under `If` of pma result

Maybe someone else sees some better solutions?

2023-11-19 14:39 UTC, piotro888 commented on coreblocks/lsu/dummyLsu.py
> +    return addr
I don't think this function is needed, it is already done inline in line 262

2023-11-19 14:39 UTC, piotro888 commented on coreblocks/params/layouts.py
> +        data_layout = layout_superset(base_data_layout, [("mmio", 1)])
Why special `layout_superset` is needed? You could just simply do list concatenation.

2023-11-19 16:11 UTC, tilk commented on coreblocks/lsu/pma.py
> +    attrs: Record
Our dataclasses are typically used at the meta-level, for generation. Records are for the circuit level only.

2023-11-19 16:11 UTC, tilk commented on coreblocks/params/configurations.py
> +    pma: List[PMARegion] = field(default_factory=list)
`List` is deprecated. Use `list`.

2023-11-19 16:21 UTC, tilk commented on transactron/utils/utils.py
> +    return base_layout + [item for item in add_layout if item[0] not in fields]
Useless complication. If needed. just concatenate.

2023-11-19 16:21 UTC, tilk commented on coreblocks/params/layouts.py
> +        data_layout = layout_superset(base_data_layout, [("mmio", 1)])
I wouldn't extend the RS structure, I would use a new one and avoid concatenation entriely.

2023-11-19 16:21 UTC, tilk commented on coreblocks/lsu/dummyLsu.py
> +                mmio_flag = pma.ask(m, addr=addr)["mmio"]
Would keep the flags in the record, and use the fields when needed.

2023-11-19 16:21 UTC, tilk commented on coreblocks/lsu/dummyLsu.py
> +                m.d.sync += current_instr.mmio.eq(mmio_flag)
A better solution would be to not use the transactional interface in PMA checking. There is no reason to use it, this is a simple combinational circuit. Also, there is a disadvantage for doing so: if the PMA checker is required in more than one place, then the PMA methods will be blocked by competing transactions. It's better to just instantiate the whole circuit again.

2023-11-19 16:49 UTC, kindlermikolaj commented on coreblocks/lsu/dummyLsu.py
> +                m.d.sync += current_instr.mmio.eq(mmio_flag)
how about something like this:
`with Transaction().body(m, request=~(current_instr.rp_s1 | current_instr.rp_s2)): 
   ...
  mmio_flag = pma.ask(m, addr=addr)["mmio"]
    ...
`
And then similar but without request condition in insert? That way we call it within method & we call it only once per instruction

2023-11-19 16:51 UTC, kindlermikolaj commented on coreblocks/params/layouts.py
> +        data_layout = layout_superset(base_data_layout, [("mmio", 1)])
The rationale behind `layout_superset` is that there is currently no instance of list concatenation in layouts, but there is `layout_subset` so having similar function that does the opposite makes sense (at least to me).

2023-11-19 16:54 UTC, kindlermikolaj commented on coreblocks/params/configurations.py
> +    pma: List[PMARegion] = field(default_factory=list)
perhaps `Iterable` would be more adequate?

2023-11-19 17:03 UTC, tilk commented on coreblocks/lsu/dummyLsu.py
> +                m.d.sync += current_instr.mmio.eq(mmio_flag)
Your suggestion is basically @piotro888's number 1. We can discuss this during the meeting, but I now believe that the transactional interface is introducing unnecessary complexity here while solving no issues at all.

2023-11-19 17:04 UTC, tilk commented on coreblocks/params/configurations.py
> +    pma: List[PMARegion] = field(default_factory=list)
No, `Iterable` is fine for function interfaces. Data structures should be concrete.

2023-11-19 17:08 UTC, piotro888 commented on coreblocks/lsu/dummyLsu.py
> +                m.d.sync += current_instr.mmio.eq(mmio_flag)
I also think now that instantiating a module is better choice here. Transactional interface is not worth the introduced complexity

2023-11-19 17:32 UTC, kindlermikolaj commented on coreblocks/params/configurations.py
> +    pma: List[PMARegion] = field(default_factory=list)
ok, done

2023-11-19 18:18 UTC, tilk commented on coreblocks/lsu/dummyLsu.py
> +        m.d.comb += is_mmio.eq(pmas["mmio"])
Combinational `Signal` has two main roles:

* Being used together with Amaranth's control structures (`m.If` etc.)
* De-duplicating expressions (as Amaranth works on trees instead of DAGs, unfortunately).

This signal is used for none of the above purposes, so a regular Python variable is enough:

```suggestion
        is_mmio = pmas["mmio"]
```

But actually, the RHS is so short and descriptive I would just consider inlining the definition at use site.

2023-11-19 18:18 UTC, tilk commented on coreblocks/lsu/dummyLsu.py
> +        m.d.comb += pmas.eq(pma_checker.result)
The attribute `pma_checker.result` is already a `Record`, you gain nothing by this. Consider just:

```suggestion
        m.d.comb += pma_checker.addr.eq(addr)
        pmas = pma_checker.result
```

Also, in case when creating a new Record is actually needed, check out `Record.like`.

2023-11-19 18:55 UTC, tilk reviewed
Looks like a pretty nice PR, the only major thing missing is a test.

2023-11-19 18:55 UTC, tilk commented on coreblocks/lsu/pma.py
> +    """
There are some superfluous newlines here.

```suggestion
    """
    Implementation of physical memory attributes checker. It may or may not be a part of LSU.
    `PMAChecker` exposes method `ask` that can be used to request information about given memory
    address. Result of `ask` method contains bit vector of all defined PMAs.

    Attributes
    ----------
    addr : Signal
        Memory address, for which PMAs are requested.
    result : Record
        PMAs for given address.
    """
```

2023-11-19 18:55 UTC, tilk commented on coreblocks/lsu/pma.py
> +
Elaboratable does not have a constructor. This is not needed, and even [Amaranth's docs](https://amaranth-lang.org/docs/amaranth/latest/start.html) show this.

2023-11-19 18:55 UTC, tilk commented on coreblocks/lsu/pma.py
> +            with m.If((self.addr >= start).bool() & (self.addr <= end).bool()):
These `.bool` don't do anything.

```suggestion
            with m.If((self.addr >= start) & (self.addr <= end)):
```

2023-11-19 18:55 UTC, tilk commented on coreblocks/lsu/pma.py
> +                m.d.comb += outputs[i].eq(0x0)
This is not needed, the default is 0.

```suggestion
```

2023-11-19 18:55 UTC, tilk commented on coreblocks/lsu/pma.py
> +            m.d.comb += self.result.eq(self.result | output)
A nitpick - could be written as:

```suggestion
        m.d.comb += self.result.eq(reduce(or_, outputs))
```

I know that Pythonists prefer iteration, but [even Guido considers using reduce with associative operators okay](https://www.artima.com/weblogs/viewpost.jsp?thread=98196).

2023-11-19 19:06 UTC, kindlermikolaj commented on coreblocks/lsu/pma.py
> +            m.d.comb += self.result.eq(self.result | output)
I didn't know that `reduce` can be applied in `Signal.eq()`

2023-12-03 17:16 UTC, lekcyjna123 commented on coreblocks/lsu/pma.py
> +        outputs = Array([Record(self.attr_layout) for _ in self.segments])
This don't have to be `Array`. Please see that in line 65 you index `outputs` with the python integer `i` not with signal. So all iterations will be done on generation time, so there is no need to include selection logic for runtime.
```suggestion
        outputs = [Record(self.attr_layout) for _ in self.segments]
```

2023-12-11 18:15 UTC, lekcyjna123 approved these changes
Logic looks ok. But I would rather see the newer syntax for TestCircuits, not legacy one (can be fixed in separate PR).

2023-12-11 18:15 UTC, lekcyjna123 commented on test/lsu/test_pma.py
> +        m.submodules.select_mock = self.select = TestbenchIO(AdapterTrans(func_unit.select))
Why you don't use `SimpleTestCircuit`?

2023-12-12 09:32 UTC, merged