DummyLSU refactored again
kuznia-rdzeni/coreblocks pull request #511
Opened 2023-11-14 10:11 UTC by tilk

I finally cleaned up this ungodly mess of wires which the DummyLSU was. There is now a clear separation of concerns: The `LSURequesterWB` handles Wishbone, and `DummyLSU` handles the LSU logic. Use of a transactional interface removed a lot of weird combinational communication.

Closes #496.

2023-11-14 18:57 UTC, lekcyjna123 commented on coreblocks/lsu/dummyLsu.py
> +        with Transaction().body(m, request=instr_ready):
Why `request=instr_ready` is needed? This transaction will be ready only if `requester.accept` will be ready, so first an `requester.issue` has been started which is already guarded by `instr_ready`.

2023-11-14 19:01 UTC, lekcyjna123 approved these changes
Now it looks much better. Whats more there are no changes in unit tests, so this is an example that our testing strategy is right.

2023-11-14 19:07 UTC, tilk commented on coreblocks/lsu/dummyLsu.py
> +        with Transaction().body(m, request=instr_ready):
You're right that this check is superfluous: if `accept` was ready and `instr_ready` was false, this would violate an (unspoken) invariant on the `issue`/`accept` interfaces of the requester, so we're in an undefined state and anything can happen.

2023-11-15 22:08 UTC, Kristopher38 requested changes
This is surprisingly very readable!
May I suggest adding a clear method for use by interrupts, or would you rather see it as a separate PR? Testing it could either wait for when we get to merge `feature/interrupts`, or alternatively tests could be taken right now from here: https://github.com/kuznia-rdzeni/coreblocks/commit/2e1326a13cdef40ba88089d5ffc340fd519af08f

2023-11-15 22:08 UTC, Kristopher38 commented on coreblocks/lsu/dummyLsu.py
> +        with Transaction().body(m, request=instr_ready & ~issued & ~instr_is_fence & (execute | instr_is_load)):
Leaving a comment on why such a `request` condition is necessary would be helpful (I get what it does after reading rest of the code but not at first glance).

2023-11-15 22:08 UTC, Kristopher38 commented on coreblocks/lsu/dummyLsu.py
> +        with Transaction().body(m, request=instr_ready & ~issued & instr_is_fence):
Same as above, simple "Handles fence as a no-op" comment would be sufficient.

2023-11-16 11:02 UTC, tilk commented
Would prefer merging this ASAP and do extensions later.

2023-11-17 09:01 UTC, Kristopher38 approved these changes

2023-11-17 09:26 UTC, merged