Autumn cleaning - remove _utils.py and utils.py in transactron
kuznia-rdzeni/coreblocks pull request #519
Opened 2023-11-19 19:14 UTC by lekcyjna123

Yet another refactor. This time I have removed files `transactron/_utils.py` and `transactron/utils/utils.py`. Content of these files was split into smaller files in `transactron/utils` directory. Please propose more meaningful file names. I don't like current but I don't have idea for other names.

2023-11-20 15:03 UTC, Arusekk requested changes
We could use the opportunity to get some better names and review if we really need some of these functions :)

2023-11-20 16:58 UTC, tilk commented on transactron/utils/functions_pythonic.py
> +def neg(x: int, xlen: int) -> int:
No, because `~C(x, xlen)` is an Amaranth value, which cannot be converted back into a Python int:
```python
>>> ~C(5,32)
(~ (const 32'd5))
>>> int(~C(5,32))
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'Operator'
>>> (~C(5,32)).value
AttributeError: 'Operator' object has no attribute 'value'
```

2023-12-15 12:24 UTC, lekcyjna123 commented on transactron/utils/functions_pythonic.py
> +def int_to_signed(x: int, xlen: int) -> int:
See: https://github.com/kuznia-rdzeni/coreblocks/pull/519#discussion_r1399495728

2023-12-15 12:24 UTC, lekcyjna123 commented on transactron/utils/functions_pythonic.py
> +def signed_to_int(x: int, xlen: int) -> int:
See: https://github.com/kuznia-rdzeni/coreblocks/pull/519#discussion_r1399495728

2023-12-15 12:27 UTC, lekcyjna123 commented on transactron/utils/functions_pythonic.py
> +    return num & ~mask
To be analysed under separate PR. Here we move a lot of code, so nothing except imports should be changed to allow for sensible review.

2023-12-15 12:27 UTC, lekcyjna123 commented on transactron/utils/functions_pythonic.py
> +    """
To be analysed under separate PR. Here we move a lot of code, so nothing except imports should be changed to allow for sensible review.

2023-12-15 12:28 UTC, lekcyjna123 commented on transactron/utils/transactron_helpers.py
> +def silence_mustuse(elaboratable: Elaboratable):
In this PR we simply move code between files, no other refactoring is done, to allow for sensible review.

2023-12-15 12:32 UTC, lekcyjna123 commented on transactron/utils/transactron_helpers.py
> +def _graph_ccs(gr: ROGraph[T]) -> list[GraphCC[T]]:
All they are used in core of transactron, so they fit together by function which they serve. In future when we have more similar functions (e.g. more graph related), then we will think how to split in in more fine grained level. As we have seen on `structs_common` predicting about files split in future is not an easy task ;)

2023-12-15 12:32 UTC, lekcyjna123 commented on transactron/utils/functions_synthesizable.py
> +from amaranth import *
I will change to `amaranth_ext`.

2023-12-15 12:42 UTC, lekcyjna123 commented on transactron/utils/modules.py
> +import itertools
I don't like the proposed names. They aren't specific enough. Please see that you proposed similar names for the other two files too.

2023-12-15 12:47 UTC, lekcyjna123 commented on transactron/utils/functions_pythonic.py
> +from collections.abc import Iterable, Mapping
I would rather not split this file to smaller one yet. I will name it `data_repr` because all of them are connected somehow with data representations (converting from python int to amaranth int and vice versa, roundings, alignments etc.)

2023-12-15 12:55 UTC, lekcyjna123 commented on transactron/utils/modules.py
> +import itertools
I have created separate subdirectory for that file and renamed it to `elaboratables`.

2023-12-15 12:56 UTC, lekcyjna123 commented on transactron/utils/functions_synthesizable.py
> +from amaranth import *
I have created `amaranth_ext` subdirectory for that file and renamed it to `functions`.

2023-12-15 14:31 UTC, tilk commented on transactron/utils/fifo.py
>  class BasicFifo(Elaboratable):
Maybe it's time to move it to lib finally?

2023-12-15 16:03 UTC, Arusekk approved these changes

2023-12-15 16:18 UTC, lekcyjna123 commented on transactron/utils/fifo.py
>  class BasicFifo(Elaboratable):
Moved

2023-12-16 11:58 UTC, tilk approved these changes

2023-12-16 11:59 UTC, merged