Add adapter module for bus
kuznia-rdzeni/coreblocks pull request #566
Opened 2024-01-15 00:02 UTC by makz00

Resolves:  #531

2024-01-15 13:49 UTC, tilk commented on coreblocks/lsu/dummyLsu.py
> +            with m.If(store_reg):
For now, to continue working on this, using `condition` instead of `m.If` will probably resolve the error. The final solution will involve changes in Transactron.

2024-01-20 00:17 UTC, makz00 commented on coreblocks/lsu/dummyLsu.py
> +            with m.If(store_reg):
Added `Serializer`

2024-01-20 00:18 UTC, makz00 commented on coreblocks/peripherals/bus_adapter.py
> +            return {"err": res.err}
Added `Serializer`

2024-01-20 00:18 UTC, makz00 commented on coreblocks/peripherals/bus_adapter.py
> +        self.def_axi_lite_methods(m)
Done

2024-01-21 13:27 UTC, piotro888 commented on coreblocks/peripherals/bus_adapter.py
> +            err = self.deduce_error(m, res.resp)
You can just write `err = res.resp != 0` or alternatively `err = res.resp.any()`
Amaranth is nice, no need to over-complicate things :)

2024-01-21 13:27 UTC, piotro888 commented on coreblocks/lsu/dummyLsu.py
> +                    pass
I don't think you want to use default condition here.
It will execute even when `aligned & store` is true, but `request_write` is not ready -> causing `self.issue` method to non-block and miss a write.
Using `with branch(~aligned):` should solve this issue (if I understand the intention correctly)

2024-01-24 13:25 UTC, tilk approved these changes
Proper AXI tests left for later.

2024-01-27 16:12 UTC, lekcyjna123 approved these changes
Only few small comments

2024-01-27 16:12 UTC, lekcyjna123 commented on coreblocks/peripherals/bus_adapter.py
> +        Readiense depends on readiense of axi lite 'ra_request' method.
Here are also typos

2024-01-27 16:12 UTC, lekcyjna123 commented on coreblocks/peripherals/wishbone.py
> +    def __init__(self, *, data_width: int = 64, addr_width: int = 64, granularity=8):
You can also add type to `granularity`

2024-01-27 16:29 UTC, tilk requested changes
Could you please fix the docstrings? I've pointed out some issues, but there is more. Also, is using a `Protocol` for the bus configurations justified?

2024-01-27 16:29 UTC, tilk commented on coreblocks/peripherals/bus_adapter.py
> +    granularity: int
Is the use of a `Protocol` necessary here? Shouldn't this just become a dataclass?

2024-01-27 16:29 UTC, tilk commented on coreblocks/peripherals/bus_adapter.py
> +        An integer that describe the granularity of accesses for parametrized bus.
```suggestion
    data_width : int
        An integer that describes the data width for a parametrized bus.
    addr_width : int
        An integer that describes the address width for a parametrized bus.
    granularity : int
        An integer that describes the granularity of accesses for parametrized bus.
```

2024-01-27 16:29 UTC, tilk commented on coreblocks/peripherals/bus_adapter.py
> +    It ease interchangeability of buses on core configuration level.
```suggestion
    The bus interface is the preferred way to gain access to a specific bus.
    It simplifies interchangeability of buses on the core configuration level.
```

2024-01-27 16:29 UTC, tilk commented on coreblocks/peripherals/bus_adapter.py
> +        A method that is used to receive the response from bus for previously sent write request.
```suggestion
    params : BusParametersInterface
        Parameters of the bus.
    request_read : Method
        A method that is used to send a read request to a bus.
    request_write : Method
        A method that is used to send a write request to a bus.
    get_read_response : Method
        A method that is used to receive the response from bus for a previously sent read request.
    get_write_response : Method
        A method that is used to receive the response from bus for a previously sent write request.
```

2024-01-27 16:29 UTC, tilk commented on coreblocks/peripherals/bus_adapter.py
> +        Layout for get_write_response method of common bus master.
```suggestion
    request_read_layout: Layout
        Layout for the request_read method of common bus master.

    request_write_layout: Layout
        Layout for the request_write method of common bus master.

    read_response_layout: Layout
        Layout for the get_read_response method of common bus master.

    write_response_layout: Layout
        Layout for the get_write_response method of common bus master.
```

2024-01-27 16:29 UTC, tilk commented on coreblocks/peripherals/bus_adapter.py
> +        Takes 'request_read_layout' as argument.
```suggestion
        Transactional method for initiating a read request.
        It is ready if the `request` method of the underlying Wishbone master is ready.
        Input layout is `request_read_layout`.
```

2024-01-27 19:12 UTC, makz00 commented on coreblocks/peripherals/bus_adapter.py
> +    granularity: int
If it would be `dataclass` then all specific buses implementations will have to use it for holding parameters. Presumably some bus can have different  parameters than other buses and then that `dataclass` will have to be extended. Please correct me if I am missing something.

With `Protocol` we specify only parameters important from Common Bus Master side point of view.

2024-01-29 09:24 UTC, tilk commented on coreblocks/peripherals/bus_adapter.py
> +    granularity: int
Let's keep it the way it is for now.

2024-01-29 09:25 UTC, tilk approved these changes

2024-01-29 09:26 UTC, tilk commented
There are conflicts to be resolved.

2024-01-29 13:30 UTC, merged