Remove private _ModuleBuilderDomain
kuznia-rdzeni/coreblocks pull request #589
Opened 2024-02-14 17:34 UTC by lekcyjna123

Hi,
based on discussion from #577, it looks like `_ModuleBuilderDomain` usage in transactron is not needed.
- typing information give us nothing, because `_ModuleBuilderDomain` in amaranth is simply a wrapper, which puts data to the correct place
- in `__setattr__` - as I understand - we check for the type to make sure that we are doing modification in place. This can be abstracted away with our internal class.

2024-02-16 12:34 UTC, tilk commented
I would much rather prefer a protocol over a wrapper.

2024-02-16 12:38 UTC, tilk commented on transactron/core.py
> +        if not isinstance(value, self._AvoidingModuleBuilderDomain):
I looked at it and I think this is nonsense (which was copied without thought from Amaranth code). If value is a `ModuleBuilderDomain`, no exception is raised, but also *nothing actually happens*. IMHO, exception should be always raised here.

2024-02-16 12:49 UTC, tilk requested changes

2024-02-16 15:48 UTC, lekcyjna123 commented on transactron/core.py
> +    class _AvoidingModuleBuilderDomain:
To prevent usage in other places. No one else in `transactron` should use that class, because it is not typed wrapper.

Amaranth doesn't nest corresponding class, but it is returned to the outside world. This is not the case in our code, because we return `_ModuleBuilderDomain` and not our wrapper.

2024-02-16 16:11 UTC, tilk commented on transactron/core.py
> +    class _AvoidingModuleBuilderDomain:
Nesting doesn't prevent usage from outside, it's not C++. The underscored name should be a good enough hint.

2024-02-19 16:46 UTC, lekcyjna123 commented on transactron/core.py
> +        def __iadd__(self, assigns):
fixed.

2024-02-19 17:51 UTC, tilk commented on transactron/core.py
> +    def __iadd__(self, assigns: list[Statement] | Statement) -> Self:
We have a more general type for that, `StatementLike`.

2024-02-26 10:28 UTC, tilk approved these changes

2024-02-27 09:35 UTC, xThaid approved these changes

2024-02-27 10:08 UTC, merged