add iterative multiplication unit
kuznia-rdzeni/coreblocks pull request #692
Opened 2024-05-02 18:39 UTC by Korbeusz

Passes standard multiplication tests

2024-05-13 12:57 UTC, tilk commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +    def __init__(self, gen_params: GenParams, dsp_width: int = 16, dsp_number: int = 8):
Verify that `dsp_width` which is not a power of 2 works.

2024-05-13 16:43 UTC, lekcyjna123 commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +    def __init__(self, gen_params: GenParams, dsp_width: int = 4, dsp_number: int = 4):
Standard `dsp_width` is 18.
See ECP5: https://www.latticesemi.com/Products/FPGAandCPLD/ECP5

2024-05-13 17:30 UTC, lekcyjna123 commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +        self.step = Signal(unsigned(n), reset=math.ceil((self.n // self.dsp_width) ** 2 / self.dsp_number))
While you use here `//` which round down?

2024-05-13 17:30 UTC, lekcyjna123 commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +        self.pipeline_array = [[[Signal(unsigned(n * 2)) for _ in range(n)] for _ in range(n)] for _ in range(n)]
It would be nice to have the signals named for the debugging purposes.

2024-05-13 17:30 UTC, lekcyjna123 commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +            m.submodules += unit
Please use named submodules. `setattr` can be useful.

2024-05-13 17:30 UTC, lekcyjna123 commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +        number_of_chunks = self.n // self.dsp_width
What with bits which left after rounding down?

2024-05-13 17:30 UTC, lekcyjna123 commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +        result_lvl = int(math.log(number_of_chunks, 2))
There is a function `math.log2` ;)

2024-05-13 17:30 UTC, lekcyjna123 commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +        self.valid_array = [Signal(unsigned(1)) for _ in range(n)]
Is all the `n` signals needed?

2024-05-13 17:30 UTC, lekcyjna123 commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +            with m.If(self.valid_array[result_lvl]):
Why this `If` is needed?

2024-05-13 17:30 UTC, lekcyjna123 commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +                m.d.sync += self.ready.eq(1)
Are you sure that `ready` should be a `sync` signal?

2024-05-13 17:30 UTC, lekcyjna123 commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +                m.d.sync += self.first_mul_number.eq(0)
A new line after `m.Else()` body will be useful.

2024-05-13 17:30 UTC, lekcyjna123 commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +            with m.If(self.first_mul_number + self.dsp_number < number_of_multiplications):
Couldn't be this `If` merged with `with m.If(self.step<number_of_steps)`? Number of multiplication and number of steps should be connected in my opinion.

2024-05-13 17:30 UTC, lekcyjna123 commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +            for i in range(number_of_multiplications):
Isn't here too many multiplications? You do `number_of_chunks**2` multiplications, but to multiply every chunk with every other it should be enought to do `(number_of_chunks**2)/2` multiplications if I count correctly.

2024-05-13 17:30 UTC, lekcyjna123 commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +                with m.If((i >= self.first_mul_number) & (i < self.first_mul_number + self.dsp_number)):
Let calculate `self.first_mul_number + self.dsp_number` outside of the loop to reduce number of additions.

2024-05-13 17:30 UTC, lekcyjna123 commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +                    dsp_idx = dsp_idx + 1
Maybe `dsp_idx = (dsp_idx+1) % self.dsp_number`?

2024-05-13 17:30 UTC, lekcyjna123 commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +                        res = self.dsp_units[dsp_idx].compute(m, i1=chunk_i1 | 0, i2=chunk_i2 | 0)
Why you do `|` with `0`?

2024-05-15 07:17 UTC, Korbeusz commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +            for i in range(number_of_multiplications):
What do you mean? If we have 3 chunks we have two numbers: "abc" and "def" and all of 9 multiplications: ad,ae,af,bd,be,bf,cd,ce,cf are needed.

2024-05-15 07:22 UTC, Korbeusz commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +                        res = self.dsp_units[dsp_idx].compute(m, i1=chunk_i1 | 0, i2=chunk_i2 | 0)
to suppress warnings see other multiplication units

2024-05-15 07:22 UTC, Korbeusz commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +                    dsp_idx = dsp_idx + 1
yes, that is better

2024-05-15 10:28 UTC, Korbeusz commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +            with m.If(self.valid_array[result_lvl]):
In the case when ready is already one but suddenly in the next cycle we are going to give valid result which when nobody is going to get data (which we do not know) the whole logic freezes which make us unable to receive input data.

2024-05-16 14:43 UTC, Korbeusz commented
This is how many cycles iterative multiplier was unable to receive new data. Tested on 100 pairs of random 4 bytes numbers:
- dsp_width:18,dsp_number:4 -> 101
- dsp_width:8,dsp_number:4 -> 202
- dsp_width:18,dsp_number:2 -> 102
- dsp_width:4,dsp_number:4 -> 803

2024-05-16 15:13 UTC, Korbeusz commented
The number of cycles consumer was idle and unable to fetch new data from iterative_multiplication.py is listed below for different parameters. Test was carried out for 100 pairs of random number each of them 4 bytes:

- dsp_width:18, dsp_number:4 -> 101
- dsp_width:18, dsp_number:2 -> 102
- dsp_width:8, dsp_number:4 -> 202
- dsp_width:4, dsp_number:4 -> 803

2024-05-16 16:40 UTC, Korbeusz commented
After "improved efficiency" commit we get:
- dsp_width:18,dsp_number:4 -> 2
- dsp_width:18,dsp_number:2 -> 102
- dsp_width:8,dsp_number:4 -> 202
- dsp_width:4,dsp_number:4 -> 803

2024-05-16 16:46 UTC, lekcyjna123 commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +            with m.If(self.valid_array[result_lvl]):
So maybe lets merge this If with the previous one?

2024-05-16 16:47 UTC, lekcyjna123 commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +            for i in range(number_of_multiplications):
Ok. You are right. I forgot that there are two different inputs.

2024-05-16 16:50 UTC, lekcyjna123 commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +                        res = self.dsp_units[dsp_idx].compute(m, i1=chunk_i1 | 0, i2=chunk_i2 | 0)
Maybe the explicit cast will be better?

2024-05-16 16:59 UTC, Korbeusz commented
There was a mistake in efficiency test those are real: I was unaware that :  `res = yield from self.m.accept.call_try()` waits one cycle itself real efficiency is:  
- dsp_width:18,dsp_number:4 -> 103
- dsp_width:18,dsp_number:2 -> 203
- dsp_width:8,dsp_number:4 -> 404
- dsp_width:4,dsp_number:4 -> 1605
In order to improve efficiency we have to make ready signal belong to m.d.comb.

2024-05-16 17:19 UTC, Korbeusz commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +                m.d.sync += self.first_mul_number.eq(0)
done

2024-05-16 17:19 UTC, Korbeusz commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +                with m.If((i >= self.first_mul_number) & (i < self.first_mul_number + self.dsp_number)):
ok

2024-05-16 17:20 UTC, Korbeusz commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +                m.d.sync += self.ready.eq(1)
yes, i am going to do it

2024-05-16 17:22 UTC, Korbeusz commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +        self.valid_array = [Signal(unsigned(1)) for _ in range(n)]
no i changed it

2024-05-16 17:22 UTC, Korbeusz commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +        result_lvl = int(math.log(number_of_chunks, 2))
ok

2024-05-16 17:22 UTC, Korbeusz commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +        number_of_chunks = self.n // self.dsp_width
Now it works

2024-05-16 17:23 UTC, Korbeusz commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +            m.submodules += unit
ok

2024-05-16 17:23 UTC, Korbeusz commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +        self.pipeline_array = [[[Signal(unsigned(n * 2)) for _ in range(n)] for _ in range(n)] for _ in range(n)]
ok

2024-05-16 17:23 UTC, Korbeusz commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +        self.step = Signal(unsigned(n), reset=math.ceil((self.n // self.dsp_width) ** 2 / self.dsp_number))
now it is done right

2024-05-16 17:23 UTC, Korbeusz commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +class IterativeSequenceMul(Elaboratable):
done

2024-05-16 17:24 UTC, Korbeusz commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +    def __init__(self, gen_params: GenParams, dsp_width: int = 16, dsp_number: int = 8):
i works now

2024-05-16 17:24 UTC, Korbeusz commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +                    m.d.sync += self.pipeline_array[0][a][b].eq(chunk_i1 * chunk_i2)
done

2024-05-16 17:24 UTC, Korbeusz commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +    def __init__(self, gen_params: GenParams, dsp_width: int = 4, dsp_number: int = 4):
now there are right

2024-05-16 17:44 UTC, Korbeusz commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +                m.d.sync += self.ready.eq(1)
I chenged ready to comb

2024-05-16 17:44 UTC, Korbeusz commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +            with m.If(self.valid_array[result_lvl]):
I changed ready to comb so problem dissolves

2024-05-16 17:50 UTC, Korbeusz commented
After efficiency improvement we get:
- dsp_width:18,dsp_number:4 -> 4
- dsp_width:18,dsp_number:2 -> 104
- dsp_width:8,dsp_number:4 -> 305
- dsp_width:4,dsp_number:4 -> 1506
I think there is no room for improvement.

2024-05-16 18:12 UTC, Korbeusz commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +            with m.If(self.first_mul_number + self.dsp_number < number_of_multiplications):
It implies the fact that order of multiplication can behave independently to number of steps from the last issue. I can merge it to one "if" but i think this way the concept would be clear.

2024-05-16 18:52 UTC, Korbeusz commented
Now we have: 

- dsp_width:18,dsp_number:4 -> 3
- dsp_width:18,dsp_number:2 -> 103
- dsp_width:8,dsp_number:4 -> 304
- dsp_width:4,dsp_number:4 -> 1505

2024-05-16 20:17 UTC, Korbeusz commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +            with m.If(self.first_mul_number + self.dsp_number < number_of_multiplications):
done

2024-05-20 16:46 UTC, lekcyjna123 approved these changes

2024-05-20 16:46 UTC, lekcyjna123 commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +        self.step = Signal(math.ceil(math.log2(self.number_of_steps) + 1), reset=self.number_of_steps)
You can use `range` in signal `Shape`. There are also `ceil_log2` and `bits_for` in `amaranth.utils`.

2024-05-20 16:46 UTC, lekcyjna123 commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +                m.d.sync += self.first_mul_number.eq(self.first_mul_number + self.dsp_number)
Are `first_mul_number` and `last_mul_number` needed at all? Yhe order of multiplication is deterministic, so you can calculate it staticaly in python and use `self.step` signal in line 114.

2024-05-20 16:46 UTC, lekcyjna123 commented on test/func_blocks/fu/test_iter_mul_unit.py
> +@parameterized_class(
I think it would be better to use parametrization from `pytest`

2024-05-20 16:56 UTC, Korbeusz commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +        self.number_of_chunks = self.n_padding // self.dsp_width
we want to have the number of chunks to always be the power of two or otherwise we would have to do different (structurally) tree every time

2024-05-20 16:57 UTC, Korbeusz commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +        self.number_of_chunks = self.n_padding // self.dsp_width
in the step where we combine multiplications to the main result

2024-05-20 16:58 UTC, Korbeusz commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +        self.number_of_chunks = self.n_padding // self.dsp_width
so n_padding is the closest bigger or equal to n number such as number of chunks is power of two

2024-05-20 17:05 UTC, Korbeusz commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +    Attributes:
ok

2024-05-20 17:06 UTC, Korbeusz commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +        step (Signal): Tracks the current iteration step in the multiplication process.
ok

2024-05-20 17:06 UTC, Korbeusz commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +        first_mul_number (Signal): Index of the first multiplication operation in the current step.
ok

2024-05-20 17:13 UTC, Korbeusz commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +        self.number_of_chunks = self.n_padding // self.dsp_width
for n=2^k n_padding is always less or equal than 2^(k+1) so it is a sensible option to me

2024-05-20 17:29 UTC, Korbeusz commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +        self.step = Signal(math.ceil(math.log2(self.number_of_steps) + 1), reset=self.number_of_steps)
ok

2024-05-20 17:38 UTC, Korbeusz commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +                m.d.sync += self.first_mul_number.eq(self.first_mul_number + self.dsp_number)
removed

2024-05-20 18:05 UTC, Korbeusz commented on test/func_blocks/fu/test_iter_mul_unit.py
> +@parameterized_class(
okay i do not know how to change it for know do you have any examples?

2024-05-27 16:16 UTC, lekcyjna123 commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +        self.number_of_chunks = self.n_padding // self.dsp_width
But as I see this cause that you do also unneeded multiplications. Based on `self.number_of_chunks` there is calculated `self.number_of_multiplications` and it is used in `self.number_of_steps`. So for the
`n=32`, `dsp_width=5` you do 64 multiplications instead of 49.

2024-05-27 18:40 UTC, Korbeusz commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +        self.number_of_chunks = self.n_padding // self.dsp_width
I fixed it

2024-06-25 18:53 UTC, piotro888 requested changes
Sorry for the late review. Great work!

Approved after resolving comments.

2024-06-25 18:53 UTC, piotro888 commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +                        m.d.sync += self.values_array[0][a][b].eq(res)
```suggestion
                run_on_step = i // self.dsp_number
                dsp_idx = i % self.dsp_number

                with Transaction().body(m, request=(self.step == run_on_step)):
                    res = self.dsp_units[dsp_idx].compute(m, i1=chunk_i1, i2=chunk_i2)
                    m.d.sync += self.values_array[0][a][b].eq(res)

```

I would suggest to simplify and clean this logic as provided:
Python `dsp_idx` assignment is not affected by Amaranth `m.If()`, so it is effectively only disabling Transaction (see `request` signal).
Values can be optimized to constants resolved  at generation, also it easier to understand (at least for me).

Please verify if I correctly understood the logic and that suggested change is equivalent.

2024-06-25 18:53 UTC, piotro888 commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +    and then combines the results using a multi-level pipeline to form the final product.
I would be for renaming the block (and file) to `PipelinedMul` or similar, as this is the most important characteristic when selecting this unit.

It can be clarified in the docstring that the first step is calculated iteratively only when there is not enough DSP units provided, lowering the pipeline throughput.

2024-06-25 18:53 UTC, piotro888 commented on test/func_blocks/fu/test_iter_mul_unit.py
> +class TestUnsignedMultiplicationUnit(TestCaseWithSimulator):
This test is only valid for this specific multiplication unit, please change the class name to reflect that, as it is the same as other generic test name.

2024-06-25 18:53 UTC, piotro888 commented on test/func_blocks/fu/test_iter_mul_unit.py
> +            assert time == 100 * math.ceil(self.number_of_multiplications / self.dsp_number) + self.pipeline_length + 2
Export `100` (here and in setup `for`) as named `self.` constant

2024-06-27 12:52 UTC, Korbeusz commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +                        m.d.sync += self.values_array[0][a][b].eq(res)
Yes, your code is equivalent and better looking. I will make this change.

2024-06-27 13:09 UTC, Korbeusz commented on coreblocks/func_blocks/fu/unsigned_multiplication/iterative_multiplication.py
> +    and then combines the results using a multi-level pipeline to form the final product.
ok

2024-06-27 13:10 UTC, Korbeusz commented on test/func_blocks/fu/test_iter_mul_unit.py
> +class TestUnsignedMultiplicationUnit(TestCaseWithSimulator):
ok

2024-06-27 13:12 UTC, Korbeusz commented on test/func_blocks/fu/test_iter_mul_unit.py
> +            assert time == 100 * math.ceil(self.number_of_multiplications / self.dsp_number) + self.pipeline_length + 2
ok

2024-06-27 14:25 UTC, piotro888 approved these changes

2024-07-03 14:15 UTC, merged