Remove func blocks unifier indirections
kuznia-rdzeni/coreblocks pull request #774
Opened 2024-12-10 16:18 UTC by tilk

This PR simplifies the announcement mechanism using the dependency system. At the same time, two layers of `Collector`s for accepting results were flattened to a single collector. The `func_blocks_unifier` module became trivial, and it might make sense to remove it later.

2024-12-13 22:14 UTC, piotro888 approved these changes

2024-12-13 22:14 UTC, piotro888 commented on test/backend/test_annoucement.py
>          # TODO: this test doesn't do anything, fix it!
Is this comment up-to-date?

2024-12-13 22:14 UTC, piotro888 commented on coreblocks/func_blocks/fu/common/rs_func_block.py
> -        self.get_result.proxy(m, collector.method)
`self.get_result` should be removed (+ in docstring too)

2024-12-13 22:18 UTC, tilk commented on test/backend/test_annoucement.py
>          # TODO: this test doesn't do anything, fix it!
I believe so. The condition in `while` looks to be false in the beginning. Maybe a negation was intended there?

2024-12-14 10:33 UTC, tilk commented on coreblocks/func_blocks/fu/common/rs_func_block.py
> -        self.get_result.proxy(m, collector.method)
Done.

2024-12-14 10:37 UTC, tilk commented on test/backend/test_annoucement.py
>          # TODO: this test doesn't do anything, fix it!
After adding the negation, the test fails. Created issue #775 for this.

2024-12-25 15:58 UTC, lekcyjna123 commented
The Fmax drop is a little bit worrying and it looks like the FuncBlockUnifier is on critical path now. I checked the synthesis results (https://github.com/kuznia-rdzeni/coreblocks/actions/runs/12359494095/job/34492356220) and it looks like:
- In sync->sync most of 30ns critical path is travelling between different parts of unifier.
- We should add registers on wishbone input from gpio. It takes 13ns to route data from GPIO and this impact LSU scheduling.
- There is a path from wishbone GPIO, LSU, FuncUnitResultKey_unifier, RF to the CSR. All that in one cycle.

2024-12-25 16:14 UTC, lekcyjna123 commented on coreblocks/func_blocks/interface/func_blocks_unifier.py
> -        self.result_collector = Collector([block.get_result for block, _ in self.rs_blocks])
If I correctly see, removing that Collector cause that all FUs get_results methods are joined with the announcement methods (so with RS and RF), which make scheduling more complex and critical path longer. In Collector there is hidden a Forwarder which cut the critical path on data.

2024-12-25 16:27 UTC, lekcyjna123 requested changes
LNGTM

The changes are affecting Fmax and make transactron network more complicated. Additionaly they removed buffers in announcement.

2024-12-25 16:27 UTC, lekcyjna123 commented on coreblocks/interface/keys.py
> +@dataclass(frozen=True)
Maybe we should start adding the doc strings to our keys? In practice they are a global variables and we haven't documented them...

2024-12-25 16:27 UTC, lekcyjna123 commented on coreblocks/func_blocks/fu/common/rs_func_block.py
> -        m.submodules.collector = collector = Collector([func_unit.accept for func_unit, _ in self.func_units])
This also complicates the transactron network. Probably its is connected with observed IPC drop. Previously, when two results were ready in the same cycle, one have been announced and second stored in Forwarder for a cycle, what made the FU ready to process the next instruction. Now the FU have to stall till it can push out its result.

2026-04-22 13:53 UTC, tilk commented
Invalid since #850 (or maybe earlier).

2026-04-22 13:53 UTC, closed without merging